// 由 internal/cmd/gencodes 依据 internal/openapi/openapi.gen.go 生成，请勿手工编辑。
// 重新生成：make generate

package alipay

// Code 是支付宝返回的业务错误码。
//
// 常量取自官方 OpenAPI 规范中各接口 ErrorResponseModel 的 code 枚举，值即
// 官方原码；未收录的码同样会被解析出来，直接比较字符串即可，不必等 SDK 更新。
//
// 注意：规范里的枚举值并非全部与线上一致。账单域已确认有出入，相关常量下方
// 标注了实测结论。交易域（ACQ.*）目前未发现不一致。做资金相关判断前，建议对
// 着真实环境验证一次错误码，不要只依赖本文件。
//
// 常量分两类：各接口自己的业务码（如 ACQ.TRADE_NOT_EXIST，大写下划线），以及每个
// 接口的 default 响应都会返回的网关公共码（如 app-call-limited，小写连字符）。
// 公共码的写法已由线上验证：未签名请求返回的 missing-timestamp 就在这张表里。
//
// 限流是公共码 app-call-limited（应用调用次数/频率超限）与 method-call-limited
// （单个接口调用次数/频率超限），不是账单域业务码 SYSTEM_RATE_LIMIT / USER_RATE_LIMIT
// ——那两个的线上写法与规范不一致（见上文），且从未在实测中出现。2026-09-07 对生产
// 网关压到 640 rps 也没触发限流，所以这两个公共码的取值只有规范背书，尚无线上样本。
type Code string

// 错误码常量，按官方原码字典序排列。
const (
	CodeACQAccessForbidden                       Code = "ACQ.ACCESS_FORBIDDEN"
	CodeACQAllocAmountValidateError              Code = "ACQ.ALLOC_AMOUNT_VALIDATE_ERROR"
	CodeACQApplyPCMerchantCodeError              Code = "ACQ.APPLY_PC_MERCHANT_CODE_ERROR"
	CodeACQBeyondPayRestriction                  Code = "ACQ.BEYOND_PAY_RESTRICTION"
	CodeACQBeyondPerReceiptDayRestriction        Code = "ACQ.BEYOND_PER_RECEIPT_DAY_RESTRICTION"
	CodeACQBeyondPerReceiptRestriction           Code = "ACQ.BEYOND_PER_RECEIPT_RESTRICTION"
	CodeACQBeyondPerReceiptSingleRestriction     Code = "ACQ.BEYOND_PER_RECEIPT_SINGLE_RESTRICTION"
	CodeACQBuyerEnableStatusForbid               Code = "ACQ.BUYER_ENABLE_STATUS_FORBID"
	CodeACQBuyerError                            Code = "ACQ.BUYER_ERROR"
	CodeACQBuyerNotExist                         Code = "ACQ.BUYER_NOT_EXIST"
	CodeACQBuyerPaymentAmountDayLimitError       Code = "ACQ.BUYER_PAYMENT_AMOUNT_DAY_LIMIT_ERROR"
	CodeACQBuyerPaymentAmountMonthLimitError     Code = "ACQ.BUYER_PAYMENT_AMOUNT_MONTH_LIMIT_ERROR"
	CodeACQBuyerSellerEqual                      Code = "ACQ.BUYER_SELLER_EQUAL"
	CodeACQContextInconsistent                   Code = "ACQ.CONTEXT_INCONSISTENT"
	CodeACQCurrencyNotSupport                    Code = "ACQ.CURRENCY_NOT_SUPPORT"
	CodeACQCustomerValidateError                 Code = "ACQ.CUSTOMER_VALIDATE_ERROR"
	CodeACQDefaultSettleRuleNotExist             Code = "ACQ.DEFAULT_SETTLE_RULE_NOT_EXIST"
	CodeACQDiscordantRepeatRequest               Code = "ACQ.DISCORDANT_REPEAT_REQUEST"
	CodeACQEnterprisePayBizError                 Code = "ACQ.ENTERPRISE_PAY_BIZ_ERROR"
	CodeACQErrorBuyerCertifyLevelLimit           Code = "ACQ.ERROR_BUYER_CERTIFY_LEVEL_LIMIT"
	CodeACQExistForbiddenWord                    Code = "ACQ.EXIST_FORBIDDEN_WORD"
	CodeACQInvalidParameter                      Code = "ACQ.INVALID_PARAMETER"
	CodeACQInvalidReceiveAccount                 Code = "ACQ.INVALID_RECEIVE_ACCOUNT"
	CodeACQInvalidStoreID                        Code = "ACQ.INVALID_STORE_ID"
	CodeACQMerchantPermReceiptDayLimit           Code = "ACQ.MERCHANT_PERM_RECEIPT_DAY_LIMIT"
	CodeACQMerchantPermReceiptSingleLimit        Code = "ACQ.MERCHANT_PERM_RECEIPT_SINGLE_LIMIT"
	CodeACQMerchantPermReceiptSuspendLimit       Code = "ACQ.MERCHANT_PERM_RECEIPT_SUSPEND_LIMIT"
	CodeACQMerchantStatusNotNormal               Code = "ACQ.MERCHANT_STATUS_NOT_NORMAL"
	CodeACQNotAllowPartialRefund                 Code = "ACQ.NOT_ALLOW_PARTIAL_REFUND"
	CodeACQNowTimeAfterExpireTimeError           Code = "ACQ.NOW_TIME_AFTER_EXPIRE_TIME_ERROR"
	CodeACQOnlineTradeVoucherNotAllowRefund      Code = "ACQ.ONLINE_TRADE_VOUCHER_NOT_ALLOW_REFUND"
	CodeACQOverdraftAgreementNotMatch            Code = "ACQ.OVERDRAFT_AGREEMENT_NOT_MATCH"
	CodeACQOverdraftAssignAccountInvalid         Code = "ACQ.OVERDRAFT_ASSIGN_ACCOUNT_INVALID"
	CodeACQPartnerError                          Code = "ACQ.PARTNER_ERROR"
	CodeACQReasonIllegalStatus                   Code = "ACQ.REASON_ILLEGAL_STATUS"
	CodeACQReasonTradeBeenFreezen                Code = "ACQ.REASON_TRADE_BEEN_FREEZEN"
	CodeACQReasonTradeRefundFeeErr               Code = "ACQ.REASON_TRADE_REFUND_FEE_ERR"
	CodeACQReasonTradeStatusInvalid              Code = "ACQ.REASON_TRADE_STATUS_INVALID"
	CodeACQRefundallocUnauthLimit                Code = "ACQ.REFUNDALLOC_UNAUTH_LIMIT"
	CodeACQRefundAccountNotExist                 Code = "ACQ.REFUND_ACCOUNT_NOT_EXIST"
	CodeACQRefundAmtNotEqualTotal                Code = "ACQ.REFUND_AMT_NOT_EQUAL_TOTAL"
	CodeACQRefundChargeError                     Code = "ACQ.REFUND_CHARGE_ERROR"
	CodeACQRefundFeeError                        Code = "ACQ.REFUND_FEE_ERROR"
	CodeACQRefundRoyaltyPayeeAccountNotExist     Code = "ACQ.REFUND_ROYALTY_PAYEE_ACCOUNT_NOT_EXIST"
	CodeACQRiskMerchantIPNotExist                Code = "ACQ.RISK_MERCHANT_IP_NOT_EXIST"
	CodeACQSecondaryMerchantAlipayAccountInvalid Code = "ACQ.SECONDARY_MERCHANT_ALIPAY_ACCOUNT_INVALID"
	CodeACQSecondaryMerchantIDBlank              Code = "ACQ.SECONDARY_MERCHANT_ID_BLANK"
	CodeACQSecondaryMerchantIDInvalid            Code = "ACQ.SECONDARY_MERCHANT_ID_INVALID"
	CodeACQSecondaryMerchantISVPunishIndirect    Code = "ACQ.SECONDARY_MERCHANT_ISV_PUNISH_INDIRECT"
	CodeACQSecondaryMerchantNotMatch             Code = "ACQ.SECONDARY_MERCHANT_NOT_MATCH"
	CodeACQSecondaryMerchantStatusError          Code = "ACQ.SECONDARY_MERCHANT_STATUS_ERROR"
	CodeACQSellerBalanceNotEnough                Code = "ACQ.SELLER_BALANCE_NOT_ENOUGH"
	CodeACQSellerBeenBlocked                     Code = "ACQ.SELLER_BEEN_BLOCKED"
	CodeACQSellerNotExist                        Code = "ACQ.SELLER_NOT_EXIST"
	CodeACQSubGoodsSizeMaxCount                  Code = "ACQ.SUB_GOODS_SIZE_MAX_COUNT"
	CodeACQSystemError                           Code = "ACQ.SYSTEM_ERROR"
	CodeACQTotalFeeExceed                        Code = "ACQ.TOTAL_FEE_EXCEED"
	CodeACQTradeBuyerNotMatch                    Code = "ACQ.TRADE_BUYER_NOT_MATCH"
	CodeACQTradeHasClose                         Code = "ACQ.TRADE_HAS_CLOSE"
	CodeACQTradeHasFinished                      Code = "ACQ.TRADE_HAS_FINISHED"
	CodeACQTradeHasSuccess                       Code = "ACQ.TRADE_HAS_SUCCESS"
	CodeACQTradeNotAllowRefund                   Code = "ACQ.TRADE_NOT_ALLOW_REFUND"
	CodeACQTradeNotExist                         Code = "ACQ.TRADE_NOT_EXIST"
	CodeACQTradeSettleError                      Code = "ACQ.TRADE_SETTLE_ERROR"
	CodeACQTradeStatusError                      Code = "ACQ.TRADE_STATUS_ERROR"
	CodeACQUserNotMatchErr                       Code = "ACQ.USER_NOT_MATCH_ERR"
	CodeBillDateBeforeRegistration               Code = "BILL_DATE_BEFORE_REGISTRATION"

	// 线上实际返回 "isp.bill_not_exist"，本常量匹配不到（2026-09-04 生产商户账号实测）
	CodeBillNotExist Code = "BILL_NOT_EXIST"

	// 线上实际返回 "invalid_arguments"，本常量匹配不到（2026-09-04 生产商户账号实测）
	CodeInvailidArguments Code = "INVAILID_ARGUMENTS"

	CodeNoBillData                         Code = "NO_BILL_DATA"
	CodeSystemRateLimit                    Code = "SYSTEM_RATE_LIMIT"
	CodeTradeNotExist                      Code = "TRADE_NOT_EXIST"
	CodeTypeNotSupported                   Code = "TYPE_NOT_SUPPORTED"
	CodeUnknownError                       Code = "UNKNOWN_ERROR"
	CodeUserRateLimit                      Code = "USER_RATE_LIMIT"
	CodeAccessDataTimeOut                  Code = "access-data-time-out"
	CodeAlipayCertNotExist                 Code = "alipay-cert-not-exist"
	CodeAppApiPunished                     Code = "app-api-punished"
	CodeAppAuthInvokeLimit                 Code = "app-auth-invoke-limit"
	CodeAppAuthTokenTimeOut                Code = "app-auth-token-time-out"
	CodeAppCallLimited                     Code = "app-call-limited"
	CodeAppCertExpired                     Code = "app-cert-expired"
	CodeAppCertNotExist                    Code = "app-cert-not-exist"
	CodeAppInvalidOid                      Code = "app-invalid-oid"
	CodeAppKeySecurityRisk                 Code = "app-key-security-risk"
	CodeAppUnbindPartner                   Code = "app-unbind-partner"
	CodeAuthTokenTimeOut                   Code = "auth-token-time-out"
	CodeDecryptionError                    Code = "decryption-error"
	CodeDecryptionErrorMissingEncryptType  Code = "decryption-error-missing-encrypt-type"
	CodeDecryptionErrorNotValidEncryptKey  Code = "decryption-error-not-valid-encrypt-key"
	CodeDecryptionErrorNotValidEncryptType Code = "decryption-error-not-valid-encrypt-type"
	CodeDecryptionErrorUnknown             Code = "decryption-error-unknown"
	CodeExceedApiBalance                   Code = "exceed-api-balance"
	CodeExistBlankSubRequestId             Code = "exist-blank-sub-request-id"
	CodeExistRepeatedSubRequestId          Code = "exist-repeated-sub-request-id"
	CodeFileCheckFail                      Code = "file-check-fail"
	CodeForbiddenApi                       Code = "forbidden-api"
	CodeIllegalCardNo                      Code = "illegal-card-no"
	CodeIllegalClientIp                    Code = "illegal-client-ip"
	CodeIllegalJson                        Code = "illegal-json"
	CodeIllegalTimestamp                   Code = "illegal-timestamp"
	CodeInnerAppNoAccess                   Code = "inner-app-no-access"
	CodeInsufficientIsvPermissions         Code = "insufficient-isv-permissions"
	CodeInsufficientUserPermissions        Code = "insufficient-user-permissions"
	CodeInvalidAlipayRootCertSn            Code = "invalid-alipay-root-cert-sn"
	CodeInvalidAppApiFieldConfig           Code = "invalid-app-api-field-config"
	CodeInvalidAppAuthRelations            Code = "invalid-app-auth-relations"
	CodeInvalidAppAuthToken                Code = "invalid-app-auth-token"
	CodeInvalidAppAuthTokenNoApi           Code = "invalid-app-auth-token-no-api"
	CodeInvalidAppId                       Code = "invalid-app-id"
	CodeInvalidAppMethod                   Code = "invalid-app-method"
	CodeInvalidAppState                    Code = "invalid-app-state"
	CodeInvalidAuthRelations               Code = "invalid-auth-relations"
	CodeInvalidAuthToken                   Code = "invalid-auth-token"
	CodeInvalidCharset                     Code = "invalid-charset"
	CodeInvalidDigest                      Code = "invalid-digest"
	CodeInvalidDigestType                  Code = "invalid-digest-type"
	CodeInvalidEncoding                    Code = "invalid-encoding"
	CodeInvalidEncrypt                     Code = "invalid-encrypt"
	CodeInvalidEncryptType                 Code = "invalid-encrypt-type"
	CodeInvalidFileExtension               Code = "invalid-file-extension"
	CodeInvalidFileSize                    Code = "invalid-file-size"
	CodeInvalidFormat                      Code = "invalid-format"
	CodeInvalidInnerInvokeScene            Code = "invalid-inner-invoke-scene"
	CodeInvalidMethod                      Code = "invalid-method"
	CodeInvalidParameter                   Code = "invalid-parameter"
	CodeInvalidPartnerid                   Code = "invalid-partnerid"
	CodeInvalidPlatform                    Code = "invalid-platform"
	CodeInvalidProduct                     Code = "invalid-product"
	CodeInvalidRequestData                 Code = "invalid-request-data"
	CodeInvalidResponseData                Code = "invalid-response-data"
	CodeInvalidSignature                   Code = "invalid-signature"
	CodeInvalidSignatureType               Code = "invalid-signature-type"
	CodeInvalidSignatureTypeSaidInterface  Code = "invalid-signature-type-said-interface"
	CodeInvalidSubscribeRelations          Code = "invalid-subscribe-relations"
	CodeInvalidTimestamp                   Code = "invalid-timestamp"
	CodeInvalidVersion                     Code = "invalid-version"
	CodeMethodCallLimited                  Code = "method-call-limited"
	CodeMethodForbiddenBatchInvoke         Code = "method-forbidden-batch-invoke"
	CodeMissingAlipayCertSn                Code = "missing-alipay-cert-sn"
	CodeMissingAlipayRootCertSn            Code = "missing-alipay-root-cert-sn"
	CodeMissingAppAccessToken              Code = "missing-app-access-token"
	CodeMissingAppCertSn                   Code = "missing-app-cert-sn"
	CodeMissingAppId                       Code = "missing-app-id"
	CodeMissingAppUid                      Code = "missing-app-uid"
	CodeMissingDefaultSignatureType        Code = "missing-default-signature-type"
	CodeMissingEncryptKey                  Code = "missing-encrypt-key"
	CodeMissingEncryptType                 Code = "missing-encrypt-type"
	CodeMissingMethod                      Code = "missing-method"
	CodeMissingPlatform                    Code = "missing-platform"
	CodeMissingSession                     Code = "missing-session"
	CodeMissingSignature                   Code = "missing-signature"
	CodeMissingSignatureConfig             Code = "missing-signature-config"
	CodeMissingSignatureKey                Code = "missing-signature-key"
	CodeMissingSignatureType               Code = "missing-signature-type"
	CodeMissingTimestamp                   Code = "missing-timestamp"
	CodeMissingVersion                     Code = "missing-version"
	CodeNoProductRegByPartner              Code = "no-product-reg-by-partner"
	CodeNotSupportAppAuth                  Code = "not-support-app-auth"
	CodeOpenidError                        Code = "openid-error"
	CodeSelfInvokeForbidden                Code = "self-invoke-forbidden"
	CodeSeviceNotBeenSubscribedTo          Code = "sevice-not-been-subscribed-to"
	CodeSuspectedAttack                    Code = "suspected-attack"
	CodeUnknowError                        Code = "unknow-error"
	CodeUnknownSubCode                     Code = "unknown-sub-code"
	CodeUnsupportOperation                 Code = "unsupport-operation"
	CodeUnsupportedExpiredAppKeySign       Code = "unsupported-expired-app-key-sign"
	CodeUnsupportedVersion                 Code = "unsupported-version"
	CodeUploadFail                         Code = "upload-fail"
)
