// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

// Defines values for AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode.
const (
	BILLDATEBEFOREREGISTRATION AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode = "BILL_DATE_BEFORE_REGISTRATION"
	BILLNOTEXIST               AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode = "BILL_NOT_EXIST"
	INVAILIDARGUMENTS          AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode = "INVAILID_ARGUMENTS"
	NOBILLDATA                 AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode = "NO_BILL_DATA"
	SYSTEMRATELIMIT            AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode = "SYSTEM_RATE_LIMIT"
	TYPENOTSUPPORTED           AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode = "TYPE_NOT_SUPPORTED"
	UNKNOWNERROR               AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode = "UNKNOWN_ERROR"
	USERRATELIMIT              AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode = "USER_RATE_LIMIT"
)

// Valid indicates whether the value is a known member of the AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode enum.
func (e AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode) Valid() bool {
	switch e {
	case BILLDATEBEFOREREGISTRATION:
		return true
	case BILLNOTEXIST:
		return true
	case INVAILIDARGUMENTS:
		return true
	case NOBILLDATA:
		return true
	case SYSTEMRATELIMIT:
		return true
	case TYPENOTSUPPORTED:
		return true
	case UNKNOWNERROR:
		return true
	case USERRATELIMIT:
		return true
	default:
		return false
	}
}

// Defines values for AlipayTradeCloseErrorResponseModelCode.
const (
	AlipayTradeCloseErrorResponseModelCodeACQINVALIDPARAMETER         AlipayTradeCloseErrorResponseModelCode = "ACQ.INVALID_PARAMETER"
	AlipayTradeCloseErrorResponseModelCodeACQREASONILLEGALSTATUS      AlipayTradeCloseErrorResponseModelCode = "ACQ.REASON_ILLEGAL_STATUS"
	AlipayTradeCloseErrorResponseModelCodeACQREASONTRADESTATUSINVALID AlipayTradeCloseErrorResponseModelCode = "ACQ.REASON_TRADE_STATUS_INVALID"
	AlipayTradeCloseErrorResponseModelCodeACQSYSTEMERROR              AlipayTradeCloseErrorResponseModelCode = "ACQ.SYSTEM_ERROR"
	AlipayTradeCloseErrorResponseModelCodeACQTRADENOTEXIST            AlipayTradeCloseErrorResponseModelCode = "ACQ.TRADE_NOT_EXIST"
	AlipayTradeCloseErrorResponseModelCodeACQTRADESTATUSERROR         AlipayTradeCloseErrorResponseModelCode = "ACQ.TRADE_STATUS_ERROR"
)

// Valid indicates whether the value is a known member of the AlipayTradeCloseErrorResponseModelCode enum.
func (e AlipayTradeCloseErrorResponseModelCode) Valid() bool {
	switch e {
	case AlipayTradeCloseErrorResponseModelCodeACQINVALIDPARAMETER:
		return true
	case AlipayTradeCloseErrorResponseModelCodeACQREASONILLEGALSTATUS:
		return true
	case AlipayTradeCloseErrorResponseModelCodeACQREASONTRADESTATUSINVALID:
		return true
	case AlipayTradeCloseErrorResponseModelCodeACQSYSTEMERROR:
		return true
	case AlipayTradeCloseErrorResponseModelCodeACQTRADENOTEXIST:
		return true
	case AlipayTradeCloseErrorResponseModelCodeACQTRADESTATUSERROR:
		return true
	default:
		return false
	}
}

// Defines values for AlipayTradeFastpayRefundQueryErrorResponseModelCode.
const (
	AlipayTradeFastpayRefundQueryErrorResponseModelCodeACQENTERPRISEPAYBIZERROR AlipayTradeFastpayRefundQueryErrorResponseModelCode = "ACQ.ENTERPRISE_PAY_BIZ_ERROR"
	AlipayTradeFastpayRefundQueryErrorResponseModelCodeACQINVALIDPARAMETER      AlipayTradeFastpayRefundQueryErrorResponseModelCode = "ACQ.INVALID_PARAMETER"
	AlipayTradeFastpayRefundQueryErrorResponseModelCodeACQSYSTEMERROR           AlipayTradeFastpayRefundQueryErrorResponseModelCode = "ACQ.SYSTEM_ERROR"
	AlipayTradeFastpayRefundQueryErrorResponseModelCodeACQTRADENOTEXIST         AlipayTradeFastpayRefundQueryErrorResponseModelCode = "ACQ.TRADE_NOT_EXIST"
	AlipayTradeFastpayRefundQueryErrorResponseModelCodeTRADENOTEXIST            AlipayTradeFastpayRefundQueryErrorResponseModelCode = "TRADE_NOT_EXIST"
)

// Valid indicates whether the value is a known member of the AlipayTradeFastpayRefundQueryErrorResponseModelCode enum.
func (e AlipayTradeFastpayRefundQueryErrorResponseModelCode) Valid() bool {
	switch e {
	case AlipayTradeFastpayRefundQueryErrorResponseModelCodeACQENTERPRISEPAYBIZERROR:
		return true
	case AlipayTradeFastpayRefundQueryErrorResponseModelCodeACQINVALIDPARAMETER:
		return true
	case AlipayTradeFastpayRefundQueryErrorResponseModelCodeACQSYSTEMERROR:
		return true
	case AlipayTradeFastpayRefundQueryErrorResponseModelCodeACQTRADENOTEXIST:
		return true
	case AlipayTradeFastpayRefundQueryErrorResponseModelCodeTRADENOTEXIST:
		return true
	default:
		return false
	}
}

// Defines values for AlipayTradePrecreateErrorResponseModelCode.
const (
	AlipayTradePrecreateErrorResponseModelCodeACQACCESSFORBIDDEN                       AlipayTradePrecreateErrorResponseModelCode = "ACQ.ACCESS_FORBIDDEN"
	AlipayTradePrecreateErrorResponseModelCodeACQAPPLYPCMERCHANTCODEERROR              AlipayTradePrecreateErrorResponseModelCode = "ACQ.APPLY_PC_MERCHANT_CODE_ERROR"
	AlipayTradePrecreateErrorResponseModelCodeACQBEYONDPAYRESTRICTION                  AlipayTradePrecreateErrorResponseModelCode = "ACQ.BEYOND_PAY_RESTRICTION"
	AlipayTradePrecreateErrorResponseModelCodeACQBEYONDPERRECEIPTDAYRESTRICTION        AlipayTradePrecreateErrorResponseModelCode = "ACQ.BEYOND_PER_RECEIPT_DAY_RESTRICTION"
	AlipayTradePrecreateErrorResponseModelCodeACQBEYONDPERRECEIPTRESTRICTION           AlipayTradePrecreateErrorResponseModelCode = "ACQ.BEYOND_PER_RECEIPT_RESTRICTION"
	AlipayTradePrecreateErrorResponseModelCodeACQBEYONDPERRECEIPTSINGLERESTRICTION     AlipayTradePrecreateErrorResponseModelCode = "ACQ.BEYOND_PER_RECEIPT_SINGLE_RESTRICTION"
	AlipayTradePrecreateErrorResponseModelCodeACQBUYERENABLESTATUSFORBID               AlipayTradePrecreateErrorResponseModelCode = "ACQ.BUYER_ENABLE_STATUS_FORBID"
	AlipayTradePrecreateErrorResponseModelCodeACQBUYERNOTEXIST                         AlipayTradePrecreateErrorResponseModelCode = "ACQ.BUYER_NOT_EXIST"
	AlipayTradePrecreateErrorResponseModelCodeACQBUYERPAYMENTAMOUNTDAYLIMITERROR       AlipayTradePrecreateErrorResponseModelCode = "ACQ.BUYER_PAYMENT_AMOUNT_DAY_LIMIT_ERROR"
	AlipayTradePrecreateErrorResponseModelCodeACQBUYERPAYMENTAMOUNTMONTHLIMITERROR     AlipayTradePrecreateErrorResponseModelCode = "ACQ.BUYER_PAYMENT_AMOUNT_MONTH_LIMIT_ERROR"
	AlipayTradePrecreateErrorResponseModelCodeACQBUYERSELLEREQUAL                      AlipayTradePrecreateErrorResponseModelCode = "ACQ.BUYER_SELLER_EQUAL"
	AlipayTradePrecreateErrorResponseModelCodeACQCONTEXTINCONSISTENT                   AlipayTradePrecreateErrorResponseModelCode = "ACQ.CONTEXT_INCONSISTENT"
	AlipayTradePrecreateErrorResponseModelCodeACQDEFAULTSETTLERULENOTEXIST             AlipayTradePrecreateErrorResponseModelCode = "ACQ.DEFAULT_SETTLE_RULE_NOT_EXIST"
	AlipayTradePrecreateErrorResponseModelCodeACQERRORBUYERCERTIFYLEVELLIMIT           AlipayTradePrecreateErrorResponseModelCode = "ACQ.ERROR_BUYER_CERTIFY_LEVEL_LIMIT"
	AlipayTradePrecreateErrorResponseModelCodeACQEXISTFORBIDDENWORD                    AlipayTradePrecreateErrorResponseModelCode = "ACQ.EXIST_FORBIDDEN_WORD"
	AlipayTradePrecreateErrorResponseModelCodeACQINVALIDPARAMETER                      AlipayTradePrecreateErrorResponseModelCode = "ACQ.INVALID_PARAMETER"
	AlipayTradePrecreateErrorResponseModelCodeACQINVALIDRECEIVEACCOUNT                 AlipayTradePrecreateErrorResponseModelCode = "ACQ.INVALID_RECEIVE_ACCOUNT"
	AlipayTradePrecreateErrorResponseModelCodeACQINVALIDSTOREID                        AlipayTradePrecreateErrorResponseModelCode = "ACQ.INVALID_STORE_ID"
	AlipayTradePrecreateErrorResponseModelCodeACQMERCHANTPERMRECEIPTDAYLIMIT           AlipayTradePrecreateErrorResponseModelCode = "ACQ.MERCHANT_PERM_RECEIPT_DAY_LIMIT"
	AlipayTradePrecreateErrorResponseModelCodeACQMERCHANTPERMRECEIPTSINGLELIMIT        AlipayTradePrecreateErrorResponseModelCode = "ACQ.MERCHANT_PERM_RECEIPT_SINGLE_LIMIT"
	AlipayTradePrecreateErrorResponseModelCodeACQMERCHANTPERMRECEIPTSUSPENDLIMIT       AlipayTradePrecreateErrorResponseModelCode = "ACQ.MERCHANT_PERM_RECEIPT_SUSPEND_LIMIT"
	AlipayTradePrecreateErrorResponseModelCodeACQMERCHANTSTATUSNOTNORMAL               AlipayTradePrecreateErrorResponseModelCode = "ACQ.MERCHANT_STATUS_NOT_NORMAL"
	AlipayTradePrecreateErrorResponseModelCodeACQNOWTIMEAFTEREXPIRETIMEERROR           AlipayTradePrecreateErrorResponseModelCode = "ACQ.NOW_TIME_AFTER_EXPIRE_TIME_ERROR"
	AlipayTradePrecreateErrorResponseModelCodeACQPARTNERERROR                          AlipayTradePrecreateErrorResponseModelCode = "ACQ.PARTNER_ERROR"
	AlipayTradePrecreateErrorResponseModelCodeACQRISKMERCHANTIPNOTEXIST                AlipayTradePrecreateErrorResponseModelCode = "ACQ.RISK_MERCHANT_IP_NOT_EXIST"
	AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTALIPAYACCOUNTINVALID AlipayTradePrecreateErrorResponseModelCode = "ACQ.SECONDARY_MERCHANT_ALIPAY_ACCOUNT_INVALID"
	AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTIDBLANK              AlipayTradePrecreateErrorResponseModelCode = "ACQ.SECONDARY_MERCHANT_ID_BLANK"
	AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTIDINVALID            AlipayTradePrecreateErrorResponseModelCode = "ACQ.SECONDARY_MERCHANT_ID_INVALID"
	AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTISVPUNISHINDIRECT    AlipayTradePrecreateErrorResponseModelCode = "ACQ.SECONDARY_MERCHANT_ISV_PUNISH_INDIRECT"
	AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTNOTMATCH             AlipayTradePrecreateErrorResponseModelCode = "ACQ.SECONDARY_MERCHANT_NOT_MATCH"
	AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTSTATUSERROR          AlipayTradePrecreateErrorResponseModelCode = "ACQ.SECONDARY_MERCHANT_STATUS_ERROR"
	AlipayTradePrecreateErrorResponseModelCodeACQSELLERBEENBLOCKED                     AlipayTradePrecreateErrorResponseModelCode = "ACQ.SELLER_BEEN_BLOCKED"
	AlipayTradePrecreateErrorResponseModelCodeACQSELLERNOTEXIST                        AlipayTradePrecreateErrorResponseModelCode = "ACQ.SELLER_NOT_EXIST"
	AlipayTradePrecreateErrorResponseModelCodeACQSUBGOODSSIZEMAXCOUNT                  AlipayTradePrecreateErrorResponseModelCode = "ACQ.SUB_GOODS_SIZE_MAX_COUNT"
	AlipayTradePrecreateErrorResponseModelCodeACQSYSTEMERROR                           AlipayTradePrecreateErrorResponseModelCode = "ACQ.SYSTEM_ERROR"
	AlipayTradePrecreateErrorResponseModelCodeACQTOTALFEEEXCEED                        AlipayTradePrecreateErrorResponseModelCode = "ACQ.TOTAL_FEE_EXCEED"
	AlipayTradePrecreateErrorResponseModelCodeACQTRADEBUYERNOTMATCH                    AlipayTradePrecreateErrorResponseModelCode = "ACQ.TRADE_BUYER_NOT_MATCH"
	AlipayTradePrecreateErrorResponseModelCodeACQTRADEHASCLOSE                         AlipayTradePrecreateErrorResponseModelCode = "ACQ.TRADE_HAS_CLOSE"
	AlipayTradePrecreateErrorResponseModelCodeACQTRADEHASSUCCESS                       AlipayTradePrecreateErrorResponseModelCode = "ACQ.TRADE_HAS_SUCCESS"
	AlipayTradePrecreateErrorResponseModelCodeACQTRADESETTLEERROR                      AlipayTradePrecreateErrorResponseModelCode = "ACQ.TRADE_SETTLE_ERROR"
)

// Valid indicates whether the value is a known member of the AlipayTradePrecreateErrorResponseModelCode enum.
func (e AlipayTradePrecreateErrorResponseModelCode) Valid() bool {
	switch e {
	case AlipayTradePrecreateErrorResponseModelCodeACQACCESSFORBIDDEN:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQAPPLYPCMERCHANTCODEERROR:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQBEYONDPAYRESTRICTION:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQBEYONDPERRECEIPTDAYRESTRICTION:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQBEYONDPERRECEIPTRESTRICTION:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQBEYONDPERRECEIPTSINGLERESTRICTION:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQBUYERENABLESTATUSFORBID:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQBUYERNOTEXIST:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQBUYERPAYMENTAMOUNTDAYLIMITERROR:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQBUYERPAYMENTAMOUNTMONTHLIMITERROR:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQBUYERSELLEREQUAL:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQCONTEXTINCONSISTENT:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQDEFAULTSETTLERULENOTEXIST:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQERRORBUYERCERTIFYLEVELLIMIT:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQEXISTFORBIDDENWORD:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQINVALIDPARAMETER:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQINVALIDRECEIVEACCOUNT:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQINVALIDSTOREID:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQMERCHANTPERMRECEIPTDAYLIMIT:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQMERCHANTPERMRECEIPTSINGLELIMIT:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQMERCHANTPERMRECEIPTSUSPENDLIMIT:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQMERCHANTSTATUSNOTNORMAL:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQNOWTIMEAFTEREXPIRETIMEERROR:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQPARTNERERROR:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQRISKMERCHANTIPNOTEXIST:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTALIPAYACCOUNTINVALID:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTIDBLANK:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTIDINVALID:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTISVPUNISHINDIRECT:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTNOTMATCH:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSECONDARYMERCHANTSTATUSERROR:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSELLERBEENBLOCKED:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSELLERNOTEXIST:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSUBGOODSSIZEMAXCOUNT:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQSYSTEMERROR:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQTOTALFEEEXCEED:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQTRADEBUYERNOTMATCH:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQTRADEHASCLOSE:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQTRADEHASSUCCESS:
		return true
	case AlipayTradePrecreateErrorResponseModelCodeACQTRADESETTLEERROR:
		return true
	default:
		return false
	}
}

// Defines values for AlipayTradeQueryErrorResponseModelCode.
const (
	AlipayTradeQueryErrorResponseModelCodeACQENTERPRISEPAYBIZERROR AlipayTradeQueryErrorResponseModelCode = "ACQ.ENTERPRISE_PAY_BIZ_ERROR"
	AlipayTradeQueryErrorResponseModelCodeACQINVALIDPARAMETER      AlipayTradeQueryErrorResponseModelCode = "ACQ.INVALID_PARAMETER"
	AlipayTradeQueryErrorResponseModelCodeACQSYSTEMERROR           AlipayTradeQueryErrorResponseModelCode = "ACQ.SYSTEM_ERROR"
	AlipayTradeQueryErrorResponseModelCodeACQTRADENOTEXIST         AlipayTradeQueryErrorResponseModelCode = "ACQ.TRADE_NOT_EXIST"
)

// Valid indicates whether the value is a known member of the AlipayTradeQueryErrorResponseModelCode enum.
func (e AlipayTradeQueryErrorResponseModelCode) Valid() bool {
	switch e {
	case AlipayTradeQueryErrorResponseModelCodeACQENTERPRISEPAYBIZERROR:
		return true
	case AlipayTradeQueryErrorResponseModelCodeACQINVALIDPARAMETER:
		return true
	case AlipayTradeQueryErrorResponseModelCodeACQSYSTEMERROR:
		return true
	case AlipayTradeQueryErrorResponseModelCodeACQTRADENOTEXIST:
		return true
	default:
		return false
	}
}

// Defines values for AlipayTradeRefundErrorResponseModelCode.
const (
	AlipayTradeRefundErrorResponseModelCodeACQALLOCAMOUNTVALIDATEERROR          AlipayTradeRefundErrorResponseModelCode = "ACQ.ALLOC_AMOUNT_VALIDATE_ERROR"
	AlipayTradeRefundErrorResponseModelCodeACQBUYERENABLESTATUSFORBID           AlipayTradeRefundErrorResponseModelCode = "ACQ.BUYER_ENABLE_STATUS_FORBID"
	AlipayTradeRefundErrorResponseModelCodeACQBUYERERROR                        AlipayTradeRefundErrorResponseModelCode = "ACQ.BUYER_ERROR"
	AlipayTradeRefundErrorResponseModelCodeACQBUYERNOTEXIST                     AlipayTradeRefundErrorResponseModelCode = "ACQ.BUYER_NOT_EXIST"
	AlipayTradeRefundErrorResponseModelCodeACQCURRENCYNOTSUPPORT                AlipayTradeRefundErrorResponseModelCode = "ACQ.CURRENCY_NOT_SUPPORT"
	AlipayTradeRefundErrorResponseModelCodeACQCUSTOMERVALIDATEERROR             AlipayTradeRefundErrorResponseModelCode = "ACQ.CUSTOMER_VALIDATE_ERROR"
	AlipayTradeRefundErrorResponseModelCodeACQDISCORDANTREPEATREQUEST           AlipayTradeRefundErrorResponseModelCode = "ACQ.DISCORDANT_REPEAT_REQUEST"
	AlipayTradeRefundErrorResponseModelCodeACQENTERPRISEPAYBIZERROR             AlipayTradeRefundErrorResponseModelCode = "ACQ.ENTERPRISE_PAY_BIZ_ERROR"
	AlipayTradeRefundErrorResponseModelCodeACQINVALIDPARAMETER                  AlipayTradeRefundErrorResponseModelCode = "ACQ.INVALID_PARAMETER"
	AlipayTradeRefundErrorResponseModelCodeACQNOTALLOWPARTIALREFUND             AlipayTradeRefundErrorResponseModelCode = "ACQ.NOT_ALLOW_PARTIAL_REFUND"
	AlipayTradeRefundErrorResponseModelCodeACQONLINETRADEVOUCHERNOTALLOWREFUND  AlipayTradeRefundErrorResponseModelCode = "ACQ.ONLINE_TRADE_VOUCHER_NOT_ALLOW_REFUND"
	AlipayTradeRefundErrorResponseModelCodeACQOVERDRAFTAGREEMENTNOTMATCH        AlipayTradeRefundErrorResponseModelCode = "ACQ.OVERDRAFT_AGREEMENT_NOT_MATCH"
	AlipayTradeRefundErrorResponseModelCodeACQOVERDRAFTASSIGNACCOUNTINVALID     AlipayTradeRefundErrorResponseModelCode = "ACQ.OVERDRAFT_ASSIGN_ACCOUNT_INVALID"
	AlipayTradeRefundErrorResponseModelCodeACQREASONTRADEBEENFREEZEN            AlipayTradeRefundErrorResponseModelCode = "ACQ.REASON_TRADE_BEEN_FREEZEN"
	AlipayTradeRefundErrorResponseModelCodeACQREASONTRADEREFUNDFEEERR           AlipayTradeRefundErrorResponseModelCode = "ACQ.REASON_TRADE_REFUND_FEE_ERR"
	AlipayTradeRefundErrorResponseModelCodeACQREASONTRADESTATUSINVALID          AlipayTradeRefundErrorResponseModelCode = "ACQ.REASON_TRADE_STATUS_INVALID"
	AlipayTradeRefundErrorResponseModelCodeACQREFUNDACCOUNTNOTEXIST             AlipayTradeRefundErrorResponseModelCode = "ACQ.REFUND_ACCOUNT_NOT_EXIST"
	AlipayTradeRefundErrorResponseModelCodeACQREFUNDALLOCUNAUTHLIMIT            AlipayTradeRefundErrorResponseModelCode = "ACQ.REFUNDALLOC_UNAUTH_LIMIT"
	AlipayTradeRefundErrorResponseModelCodeACQREFUNDAMTNOTEQUALTOTAL            AlipayTradeRefundErrorResponseModelCode = "ACQ.REFUND_AMT_NOT_EQUAL_TOTAL"
	AlipayTradeRefundErrorResponseModelCodeACQREFUNDCHARGEERROR                 AlipayTradeRefundErrorResponseModelCode = "ACQ.REFUND_CHARGE_ERROR"
	AlipayTradeRefundErrorResponseModelCodeACQREFUNDFEEERROR                    AlipayTradeRefundErrorResponseModelCode = "ACQ.REFUND_FEE_ERROR"
	AlipayTradeRefundErrorResponseModelCodeACQREFUNDROYALTYPAYEEACCOUNTNOTEXIST AlipayTradeRefundErrorResponseModelCode = "ACQ.REFUND_ROYALTY_PAYEE_ACCOUNT_NOT_EXIST"
	AlipayTradeRefundErrorResponseModelCodeACQSELLERBALANCENOTENOUGH            AlipayTradeRefundErrorResponseModelCode = "ACQ.SELLER_BALANCE_NOT_ENOUGH"
	AlipayTradeRefundErrorResponseModelCodeACQSYSTEMERROR                       AlipayTradeRefundErrorResponseModelCode = "ACQ.SYSTEM_ERROR"
	AlipayTradeRefundErrorResponseModelCodeACQTRADEHASCLOSE                     AlipayTradeRefundErrorResponseModelCode = "ACQ.TRADE_HAS_CLOSE"
	AlipayTradeRefundErrorResponseModelCodeACQTRADEHASFINISHED                  AlipayTradeRefundErrorResponseModelCode = "ACQ.TRADE_HAS_FINISHED"
	AlipayTradeRefundErrorResponseModelCodeACQTRADENOTALLOWREFUND               AlipayTradeRefundErrorResponseModelCode = "ACQ.TRADE_NOT_ALLOW_REFUND"
	AlipayTradeRefundErrorResponseModelCodeACQTRADENOTEXIST                     AlipayTradeRefundErrorResponseModelCode = "ACQ.TRADE_NOT_EXIST"
	AlipayTradeRefundErrorResponseModelCodeACQTRADESETTLEERROR                  AlipayTradeRefundErrorResponseModelCode = "ACQ.TRADE_SETTLE_ERROR"
	AlipayTradeRefundErrorResponseModelCodeACQTRADESTATUSERROR                  AlipayTradeRefundErrorResponseModelCode = "ACQ.TRADE_STATUS_ERROR"
	AlipayTradeRefundErrorResponseModelCodeACQUSERNOTMATCHERR                   AlipayTradeRefundErrorResponseModelCode = "ACQ.USER_NOT_MATCH_ERR"
)

// Valid indicates whether the value is a known member of the AlipayTradeRefundErrorResponseModelCode enum.
func (e AlipayTradeRefundErrorResponseModelCode) Valid() bool {
	switch e {
	case AlipayTradeRefundErrorResponseModelCodeACQALLOCAMOUNTVALIDATEERROR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQBUYERENABLESTATUSFORBID:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQBUYERERROR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQBUYERNOTEXIST:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQCURRENCYNOTSUPPORT:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQCUSTOMERVALIDATEERROR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQDISCORDANTREPEATREQUEST:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQENTERPRISEPAYBIZERROR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQINVALIDPARAMETER:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQNOTALLOWPARTIALREFUND:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQONLINETRADEVOUCHERNOTALLOWREFUND:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQOVERDRAFTAGREEMENTNOTMATCH:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQOVERDRAFTASSIGNACCOUNTINVALID:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQREASONTRADEBEENFREEZEN:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQREASONTRADEREFUNDFEEERR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQREASONTRADESTATUSINVALID:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQREFUNDACCOUNTNOTEXIST:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQREFUNDALLOCUNAUTHLIMIT:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQREFUNDAMTNOTEQUALTOTAL:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQREFUNDCHARGEERROR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQREFUNDFEEERROR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQREFUNDROYALTYPAYEEACCOUNTNOTEXIST:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQSELLERBALANCENOTENOUGH:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQSYSTEMERROR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQTRADEHASCLOSE:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQTRADEHASFINISHED:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQTRADENOTALLOWREFUND:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQTRADENOTEXIST:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQTRADESETTLEERROR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQTRADESTATUSERROR:
		return true
	case AlipayTradeRefundErrorResponseModelCodeACQUSERNOTMATCHERR:
		return true
	default:
		return false
	}
}

// Defines values for CommonErrorTypeCode.
const (
	AccessDataTimeOut                  CommonErrorTypeCode = "access-data-time-out"
	AlipayCertNotExist                 CommonErrorTypeCode = "alipay-cert-not-exist"
	AppApiPunished                     CommonErrorTypeCode = "app-api-punished"
	AppAuthInvokeLimit                 CommonErrorTypeCode = "app-auth-invoke-limit"
	AppAuthTokenTimeOut                CommonErrorTypeCode = "app-auth-token-time-out"
	AppCallLimited                     CommonErrorTypeCode = "app-call-limited"
	AppCertNotExist                    CommonErrorTypeCode = "app-cert-not-exist"
	AppInvalidOid                      CommonErrorTypeCode = "app-invalid-oid"
	AppKeySecurityRiskAppCertExpired   CommonErrorTypeCode = "app-key-security-risk, app-cert-expired"
	AppUnbindPartner                   CommonErrorTypeCode = "app-unbind-partner"
	AuthTokenTimeOut                   CommonErrorTypeCode = "auth-token-time-out"
	DecryptionError                    CommonErrorTypeCode = "decryption-error"
	DecryptionErrorMissingEncryptType  CommonErrorTypeCode = "decryption-error-missing-encrypt-type"
	DecryptionErrorNotValidEncryptKey  CommonErrorTypeCode = "decryption-error-not-valid-encrypt-key"
	DecryptionErrorNotValidEncryptType CommonErrorTypeCode = "decryption-error-not-valid-encrypt-type"
	DecryptionErrorUnknown             CommonErrorTypeCode = "decryption-error-unknown"
	ExceedApiBalance                   CommonErrorTypeCode = "exceed-api-balance"
	ExistBlankSubRequestId             CommonErrorTypeCode = "exist-blank-sub-request-id"
	ExistRepeatedSubRequestId          CommonErrorTypeCode = "exist-repeated-sub-request-id"
	FileCheckFail                      CommonErrorTypeCode = "file-check-fail"
	ForbiddenApi                       CommonErrorTypeCode = "forbidden-api"
	IllegalCardNo                      CommonErrorTypeCode = "illegal-card-no"
	IllegalClientIp                    CommonErrorTypeCode = "illegal-client-ip"
	IllegalJson                        CommonErrorTypeCode = "illegal-json"
	IllegalTimestamp                   CommonErrorTypeCode = "illegal-timestamp"
	InnerAppNoAccess                   CommonErrorTypeCode = "inner-app-no-access"
	InsufficientIsvPermissions         CommonErrorTypeCode = "insufficient-isv-permissions"
	InsufficientUserPermissions        CommonErrorTypeCode = "insufficient-user-permissions"
	InvalidAlipayRootCertSn            CommonErrorTypeCode = "invalid-alipay-root-cert-sn"
	InvalidAppApiFieldConfig           CommonErrorTypeCode = "invalid-app-api-field-config"
	InvalidAppAuthRelations            CommonErrorTypeCode = "invalid-app-auth-relations"
	InvalidAppAuthToken                CommonErrorTypeCode = "invalid-app-auth-token"
	InvalidAppAuthTokenNoApi           CommonErrorTypeCode = "invalid-app-auth-token-no-api"
	InvalidAppId                       CommonErrorTypeCode = "invalid-app-id"
	InvalidAppMethod                   CommonErrorTypeCode = "invalid-app-method"
	InvalidAppState                    CommonErrorTypeCode = "invalid-app-state"
	InvalidAuthRelations               CommonErrorTypeCode = "invalid-auth-relations"
	InvalidAuthToken                   CommonErrorTypeCode = "invalid-auth-token"
	InvalidCharset                     CommonErrorTypeCode = "invalid-charset"
	InvalidDigest                      CommonErrorTypeCode = "invalid-digest"
	InvalidDigestType                  CommonErrorTypeCode = "invalid-digest-type"
	InvalidEncoding                    CommonErrorTypeCode = "invalid-encoding"
	InvalidEncrypt                     CommonErrorTypeCode = "invalid-encrypt"
	InvalidEncryptType                 CommonErrorTypeCode = "invalid-encrypt-type"
	InvalidFileExtension               CommonErrorTypeCode = "invalid-file-extension"
	InvalidFileSize                    CommonErrorTypeCode = "invalid-file-size"
	InvalidFormat                      CommonErrorTypeCode = "invalid-format"
	InvalidInnerInvokeScene            CommonErrorTypeCode = "invalid-inner-invoke-scene"
	InvalidMethod                      CommonErrorTypeCode = "invalid-method"
	InvalidParameter                   CommonErrorTypeCode = "invalid-parameter"
	InvalidPartnerid                   CommonErrorTypeCode = "invalid-partnerid"
	InvalidPlatform                    CommonErrorTypeCode = "invalid-platform"
	InvalidProduct                     CommonErrorTypeCode = "invalid-product"
	InvalidRequestData                 CommonErrorTypeCode = "invalid-request-data"
	InvalidResponseData                CommonErrorTypeCode = "invalid-response-data"
	InvalidSignature                   CommonErrorTypeCode = "invalid-signature"
	InvalidSignatureType               CommonErrorTypeCode = "invalid-signature-type"
	InvalidSignatureTypeSaidInterface  CommonErrorTypeCode = "invalid-signature-type-said-interface"
	InvalidSubscribeRelations          CommonErrorTypeCode = "invalid-subscribe-relations"
	InvalidTimestamp                   CommonErrorTypeCode = "invalid-timestamp"
	InvalidVersion                     CommonErrorTypeCode = "invalid-version"
	MethodCallLimited                  CommonErrorTypeCode = "method-call-limited"
	MethodForbiddenBatchInvoke         CommonErrorTypeCode = "method-forbidden-batch-invoke"
	MissingAlipayCertSn                CommonErrorTypeCode = "missing-alipay-cert-sn"
	MissingAlipayRootCertSn            CommonErrorTypeCode = "missing-alipay-root-cert-sn"
	MissingAppAccessToken              CommonErrorTypeCode = "missing-app-access-token"
	MissingAppCertSn                   CommonErrorTypeCode = "missing-app-cert-sn"
	MissingAppId                       CommonErrorTypeCode = "missing-app-id"
	MissingAppUid                      CommonErrorTypeCode = "missing-app-uid"
	MissingDefaultSignatureType        CommonErrorTypeCode = "missing-default-signature-type"
	MissingEncryptKey                  CommonErrorTypeCode = "missing-encrypt-key"
	MissingEncryptType                 CommonErrorTypeCode = "missing-encrypt-type"
	MissingMethod                      CommonErrorTypeCode = "missing-method"
	MissingPlatform                    CommonErrorTypeCode = "missing-platform"
	MissingSession                     CommonErrorTypeCode = "missing-session"
	MissingSignature                   CommonErrorTypeCode = "missing-signature"
	MissingSignatureConfig             CommonErrorTypeCode = "missing-signature-config"
	MissingSignatureKey                CommonErrorTypeCode = "missing-signature-key"
	MissingSignatureType               CommonErrorTypeCode = "missing-signature-type"
	MissingTimestamp                   CommonErrorTypeCode = "missing-timestamp"
	MissingVersion                     CommonErrorTypeCode = "missing-version"
	NoProductRegByPartner              CommonErrorTypeCode = "no-product-reg-by-partner"
	NotSupportAppAuth                  CommonErrorTypeCode = "not-support-app-auth"
	OpenidError                        CommonErrorTypeCode = "openid-error"
	SelfInvokeForbidden                CommonErrorTypeCode = "self-invoke-forbidden"
	SeviceNotBeenSubscribedTo          CommonErrorTypeCode = "sevice-not-been-subscribed-to"
	SuspectedAttack                    CommonErrorTypeCode = "suspected-attack"
	UnknowError                        CommonErrorTypeCode = "unknow-error"
	UnknownSubCode                     CommonErrorTypeCode = "unknown-sub-code"
	UnsupportOperation                 CommonErrorTypeCode = "unsupport-operation"
	UnsupportedExpiredAppKeySign       CommonErrorTypeCode = "unsupported-expired-app-key-sign"
	UnsupportedVersion                 CommonErrorTypeCode = "unsupported-version"
	UploadFail                         CommonErrorTypeCode = "upload-fail"
)

// Valid indicates whether the value is a known member of the CommonErrorTypeCode enum.
func (e CommonErrorTypeCode) Valid() bool {
	switch e {
	case AccessDataTimeOut:
		return true
	case AlipayCertNotExist:
		return true
	case AppApiPunished:
		return true
	case AppAuthInvokeLimit:
		return true
	case AppAuthTokenTimeOut:
		return true
	case AppCallLimited:
		return true
	case AppCertNotExist:
		return true
	case AppInvalidOid:
		return true
	case AppKeySecurityRiskAppCertExpired:
		return true
	case AppUnbindPartner:
		return true
	case AuthTokenTimeOut:
		return true
	case DecryptionError:
		return true
	case DecryptionErrorMissingEncryptType:
		return true
	case DecryptionErrorNotValidEncryptKey:
		return true
	case DecryptionErrorNotValidEncryptType:
		return true
	case DecryptionErrorUnknown:
		return true
	case ExceedApiBalance:
		return true
	case ExistBlankSubRequestId:
		return true
	case ExistRepeatedSubRequestId:
		return true
	case FileCheckFail:
		return true
	case ForbiddenApi:
		return true
	case IllegalCardNo:
		return true
	case IllegalClientIp:
		return true
	case IllegalJson:
		return true
	case IllegalTimestamp:
		return true
	case InnerAppNoAccess:
		return true
	case InsufficientIsvPermissions:
		return true
	case InsufficientUserPermissions:
		return true
	case InvalidAlipayRootCertSn:
		return true
	case InvalidAppApiFieldConfig:
		return true
	case InvalidAppAuthRelations:
		return true
	case InvalidAppAuthToken:
		return true
	case InvalidAppAuthTokenNoApi:
		return true
	case InvalidAppId:
		return true
	case InvalidAppMethod:
		return true
	case InvalidAppState:
		return true
	case InvalidAuthRelations:
		return true
	case InvalidAuthToken:
		return true
	case InvalidCharset:
		return true
	case InvalidDigest:
		return true
	case InvalidDigestType:
		return true
	case InvalidEncoding:
		return true
	case InvalidEncrypt:
		return true
	case InvalidEncryptType:
		return true
	case InvalidFileExtension:
		return true
	case InvalidFileSize:
		return true
	case InvalidFormat:
		return true
	case InvalidInnerInvokeScene:
		return true
	case InvalidMethod:
		return true
	case InvalidParameter:
		return true
	case InvalidPartnerid:
		return true
	case InvalidPlatform:
		return true
	case InvalidProduct:
		return true
	case InvalidRequestData:
		return true
	case InvalidResponseData:
		return true
	case InvalidSignature:
		return true
	case InvalidSignatureType:
		return true
	case InvalidSignatureTypeSaidInterface:
		return true
	case InvalidSubscribeRelations:
		return true
	case InvalidTimestamp:
		return true
	case InvalidVersion:
		return true
	case MethodCallLimited:
		return true
	case MethodForbiddenBatchInvoke:
		return true
	case MissingAlipayCertSn:
		return true
	case MissingAlipayRootCertSn:
		return true
	case MissingAppAccessToken:
		return true
	case MissingAppCertSn:
		return true
	case MissingAppId:
		return true
	case MissingAppUid:
		return true
	case MissingDefaultSignatureType:
		return true
	case MissingEncryptKey:
		return true
	case MissingEncryptType:
		return true
	case MissingMethod:
		return true
	case MissingPlatform:
		return true
	case MissingSession:
		return true
	case MissingSignature:
		return true
	case MissingSignatureConfig:
		return true
	case MissingSignatureKey:
		return true
	case MissingSignatureType:
		return true
	case MissingTimestamp:
		return true
	case MissingVersion:
		return true
	case NoProductRegByPartner:
		return true
	case NotSupportAppAuth:
		return true
	case OpenidError:
		return true
	case SelfInvokeForbidden:
		return true
	case SeviceNotBeenSubscribedTo:
		return true
	case SuspectedAttack:
		return true
	case UnknowError:
		return true
	case UnknownSubCode:
		return true
	case UnsupportOperation:
		return true
	case UnsupportedExpiredAppKeySign:
		return true
	case UnsupportedVersion:
		return true
	case UploadFail:
		return true
	default:
		return false
	}
}

// AlipayDataDataserviceBillDownloadurlQueryErrorResponseModel defines model for AlipayDataDataserviceBillDownloadurlQueryErrorResponseModel.
type AlipayDataDataserviceBillDownloadurlQueryErrorResponseModel struct {
	// Code 错误码
	Code AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode `json:"code"`

	// Links 解决方案链接
	Links *string `json:"links,omitempty"`

	// Message 错误描述
	Message string `json:"message"`
}

// AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode 错误码
type AlipayDataDataserviceBillDownloadurlQueryErrorResponseModelCode string

// AlipayDataDataserviceBillDownloadurlQueryResponseModel defines model for AlipayDataDataserviceBillDownloadurlQueryResponseModel.
type AlipayDataDataserviceBillDownloadurlQueryResponseModel struct {
	// BillDownloadUrl 当账单可获取时，返回账单下载地址链接，获取链接后30秒后未下载，链接地址失效。
	//
	// Example: http://dwbillcenter.alipay.com/downloadBillFile.resource?bizType=X&pid=X&fileType=X&bizDates=X&downloadFileName=X&fileId=X
	BillDownloadUrl *string `json:"bill_download_url,omitempty"`

	// BillFileCode 描述本次申请的账单文件状态。	EMPTY_DATA_WITH_BILL_FILE：当天无账单业务数据&&可以获取到空数据账单文件。
	//
	// Example: EMPTY_DATA_WITH_BILL_FILE
	BillFileCode *string `json:"bill_file_code,omitempty"`
}

// AlipayTradeCloseErrorResponseModel defines model for AlipayTradeCloseErrorResponseModel.
type AlipayTradeCloseErrorResponseModel struct {
	// Code 错误码
	Code AlipayTradeCloseErrorResponseModelCode `json:"code"`

	// Links 解决方案链接
	Links *string `json:"links,omitempty"`

	// Message 错误描述
	Message string `json:"message"`
}

// AlipayTradeCloseErrorResponseModelCode 错误码
type AlipayTradeCloseErrorResponseModelCode string

// AlipayTradeCloseModel defines model for AlipayTradeCloseModel.
type AlipayTradeCloseModel struct {
	ExtendParams *CloseExtendParams `json:"extend_params,omitempty"`

	// NotifyUrl 通知地址
	NotifyUrl *string `json:"notify_url,omitempty"`

	// OperatorId 商家操作员编号 id，由商家自定义。
	//
	// Example: YX01
	OperatorId *string `json:"operator_id,omitempty"`

	// OutTradeNo 订单支付时传入的商户订单号,和支付宝交易号不能同时为空。 trade_no,out_trade_no如果同时存在优先取trade_no
	//
	// Example: HZ0120131127001
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// TradeNo 该交易在支付宝系统中的交易流水号。最短 16 位，最长 64 位。和out_trade_no不能同时为空，如果同时传了 out_trade_no和 trade_no，则以 trade_no为准。
	//
	// Example: 2013112611001004680073956707
	TradeNo *string `json:"trade_no,omitempty"`
}

// AlipayTradeCloseResponseModel defines model for AlipayTradeCloseResponseModel.
type AlipayTradeCloseResponseModel struct {
	// OutTradeNo 创建交易传入的商户订单号
	//
	// Example: YX_001
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// TradeNo 支付宝交易号
	//
	// Example: 2013112111001004500000675971
	TradeNo *string `json:"trade_no,omitempty"`
}

// AlipayTradeFastpayRefundQueryErrorResponseModel defines model for AlipayTradeFastpayRefundQueryErrorResponseModel.
type AlipayTradeFastpayRefundQueryErrorResponseModel struct {
	// Code 错误码
	Code AlipayTradeFastpayRefundQueryErrorResponseModelCode `json:"code"`

	// Links 解决方案链接
	Links *string `json:"links,omitempty"`

	// Message 错误描述
	Message string `json:"message"`
}

// AlipayTradeFastpayRefundQueryErrorResponseModelCode 错误码
type AlipayTradeFastpayRefundQueryErrorResponseModelCode string

// AlipayTradeFastpayRefundQueryModel defines model for AlipayTradeFastpayRefundQueryModel.
type AlipayTradeFastpayRefundQueryModel struct {
	// OrgPid 银行间联模式下有用，其它场景请不要使用；
	// 	双联通过该参数指定需要查询的交易所属收单机构的pid;
	//
	// Example: 2088101117952222
	OrgPid *string `json:"org_pid,omitempty"`

	// OutRequestNo 退款请求号。	请求退款接口时，传入的退款请求号，如果在退款请求时未传入，则该值为创建交易时的商户订单号。
	//
	// Example: HZ01RF001
	OutRequestNo *string `json:"out_request_no,omitempty"`

	// OutTradeNo 商户订单号。	订单支付时传入的商户订单号,和支付宝交易号不能同时为空。 trade_no,out_trade_no如果同时存在优先取trade_no
	//
	// Example: 2014112611001004680073956707
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// QueryOptions 查询选项，商户通过上送该参数来定制同步需要额外返回的信息字段，数组格式。枚举支持：	refund_detail_item_list：本次退款使用的资金渠道；	gmt_refund_pay：退款执行成功的时间；	deposit_back_info：银行卡冲退信息；
	//
	// Example: ["refund_detail_item_list"]
	QueryOptions *[]string `json:"query_options,omitempty"`

	// TradeNo 支付宝交易号。	和商户订单号不能同时为空
	//
	// Example: 2021081722001419121412730660
	TradeNo *string `json:"trade_no,omitempty"`
}

// AlipayTradeFastpayRefundQueryResponseModel defines model for AlipayTradeFastpayRefundQueryResponseModel.
type AlipayTradeFastpayRefundQueryResponseModel struct {
	DepositBackInfo *DepositBackInfo `json:"deposit_back_info,omitempty"`

	// DepositBackInfoList 银行卡冲退信息列表。	默认不返回该信息，需要在入参的query_options中指定"deposit_back_info_list"值时才返回该字段信息。
	DepositBackInfoList *[]DepositBackInfo `json:"deposit_back_info_list,omitempty"`
	EnterprisePayInfo   *EnterprisePayInfo `json:"enterprise_pay_info,omitempty"`

	// ErrorCode 退款失败错误码。只在使用异步退款接口情况下才会返回该字段
	//
	// Example: SELLER_BALANCE_NOT_ENOUGH
	ErrorCode *string `json:"error_code,omitempty"`

	// GmtRefundPay 退款时间。默认不返回该信息，需要在入参的query_options中指定"gmt_refund_pay"值时才返回该字段信息。
	//
	// Example: 2014-11-27 15:45:57
	GmtRefundPay *string `json:"gmt_refund_pay,omitempty"`

	// IndustrySepcDetail 行业特殊信息（例如在医保卡支付退款中，医保局向商户返回医疗信息）。
	//
	// Example: [{"bizType":"REFUND","modelName":"tradeCancelContext","contextData":{"response_content":"{\"WxResToll\":{\"dealID\":\"\",}}"}}]
	IndustrySepcDetail *string `json:"industry_sepc_detail,omitempty"`

	// OutRequestNo 本笔退款对应的退款请求号
	//
	// Example: 20150320010101001
	OutRequestNo *string `json:"out_request_no,omitempty"`

	// OutTradeNo 创建交易传入的商户订单号
	//
	// Example: 20150320010101001
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// PreAuthCancelFee 当用户使用芝麻信用先享后付时，且当前的操作为预授权撤销动作时，会返回该字段，代表当前撤销的预授权金额，单位元。
	//
	// Example: 12.45
	PreAuthCancelFee *string `json:"pre_auth_cancel_fee,omitempty"`

	// PresentRefundBuyerAmount 本次退款金额中买家退款金额。单位：元。	该字段默认不返回；
	//
	// Example: 88.88
	PresentRefundBuyerAmount *string `json:"present_refund_buyer_amount,omitempty"`

	// PresentRefundDiscountAmount 本次退款金额中平台优惠退款金额。单位：元。	该字段默认不返回；
	//
	// Example: 88.88
	PresentRefundDiscountAmount *string `json:"present_refund_discount_amount,omitempty"`

	// PresentRefundMdiscountAmount 本次退款金额中商家优惠退款金额。单位：元。	该字段默认不返回；
	//
	// Example: 88.88
	PresentRefundMdiscountAmount *string `json:"present_refund_mdiscount_amount,omitempty"`

	// RefundAmount 本次退款请求，对应的退款金额。单位：元。
	//
	// Example: 12.33
	RefundAmount *string `json:"refund_amount,omitempty"`

	// RefundChannelList 若支付渠道包含医保统筹、个账，则显示退款的渠道信息。如统筹OUTSIDEGOVCARD，个账OUTSIDEACCCARD
	//
	// Example: OUTSIDEGOVCARD
	RefundChannelList *string `json:"refund_channel_list,omitempty"`

	// RefundChannelStatus 若支付渠道包含医保统筹、个账，全渠道退款成功时返回SUCCESS，全失败时返回FAIL，部分成功时返回PART_SUCCESS
	//
	// Example: SUCCESS
	RefundChannelStatus *string `json:"refund_channel_status,omitempty"`

	// RefundChargeAmount 本次退款针对收款方的退收费金额；单位：元。	只在机构间联模式下返回，其它场景下不返回该字段；
	//
	// Example: 8.88
	RefundChargeAmount *string `json:"refund_charge_amount,omitempty"`

	// RefundChargeInfoList 退费信息
	RefundChargeInfoList *[]RefundChargeInfo `json:"refund_charge_info_list,omitempty"`

	// RefundDetailItemList 本次退款使用的资金渠道；	默认不返回该信息，需要在入参的query_options中指定"refund_detail_item_list"值时才返回该字段信息。
	RefundDetailItemList *[]TradeFundBill `json:"refund_detail_item_list,omitempty"`

	// RefundHybAmount 本次退款金额中退惠营宝的金额。单位：元。
	//
	// Example: 10.24
	RefundHybAmount *string `json:"refund_hyb_amount,omitempty"`

	// RefundReason 发起退款时，传入的退款原因
	//
	// Example: 用户退款请求
	RefundReason *string `json:"refund_reason,omitempty"`

	// RefundRoyaltys 退分账明细信息，当前仅在直付通产品中返回。
	RefundRoyaltys *[]RefundRoyaltyResult `json:"refund_royaltys,omitempty"`

	// RefundSettlementId 退款清算编号，用于清算对账使用；	只在机构间联模式下返回，其它场景下不返回该字段；
	//
	// Example: 2018101610032004620239146945
	RefundSettlementId *string `json:"refund_settlement_id,omitempty"`

	// RefundStatus 退款状态。枚举值：	REFUND_SUCCESS 退款处理成功；	未返回该字段表示退款请求未收到或者退款失败；	注：如果退款查询发起时间早于退款时间，或者间隔退款发起时间太短，可能出现退款查询时还没处理成功，后面又处理成功的情况，建议商户在退款发起后间隔10秒以上再发起退款查询请求。
	//
	// Example: REFUND_SUCCESS
	RefundStatus *string `json:"refund_status,omitempty"`

	// RefundVoucherDetailList 本交易支付时使用的所有优惠券信息。 只有在query_options中指定refund_voucher_detail_list时才返回该字段信息。
	RefundVoucherDetailList *[]VoucherDetail `json:"refund_voucher_detail_list,omitempty"`

	// SendBackFee 本次商户实际退回金额；单位：元。	默认不返回该信息，需要在入参的query_options中指定"refund_detail_item_list"值时才返回该字段信息。
	//
	// Example: 88
	SendBackFee *string `json:"send_back_fee,omitempty"`

	// TotalAmount 该笔退款所对应的交易的订单金额。单位：元。
	//
	// Example: 100.20
	TotalAmount *string `json:"total_amount,omitempty"`

	// TradeNo 支付宝交易号
	//
	// Example: 2014112611001004680073956707
	TradeNo *string `json:"trade_no,omitempty"`
}

// AlipayTradePrecreateErrorResponseModel defines model for AlipayTradePrecreateErrorResponseModel.
type AlipayTradePrecreateErrorResponseModel struct {
	// Code 错误码
	Code AlipayTradePrecreateErrorResponseModelCode `json:"code"`

	// Links 解决方案链接
	Links *string `json:"links,omitempty"`

	// Message 错误描述
	Message string `json:"message"`
}

// AlipayTradePrecreateErrorResponseModelCode 错误码
type AlipayTradePrecreateErrorResponseModelCode string

// AlipayTradePrecreateModel defines model for AlipayTradePrecreateModel.
type AlipayTradePrecreateModel struct {
	// AlipayStoreId 支付宝店铺编号。	指商户创建门店后支付宝生成的门店ID。
	//
	// Example: 2016052600077000000015640104
	AlipayStoreId  *string         `json:"alipay_store_id,omitempty"`
	BkagentReqInfo *BkAgentReqInfo `json:"bkagent_req_info,omitempty"`

	// Body 订单附加信息。	如果请求时传递了该参数，将在异步通知、对账单中原样返回，同时会在商户和用户的pc账单详情中作为交易描述展示
	//
	// Example: Iphone6 16G
	Body           *string         `json:"body,omitempty"`
	BusinessParams *BusinessParams `json:"business_params,omitempty"`

	// BuyerLogonId 买家支付宝账号
	//
	// Example: 15901825620
	BuyerLogonId *string `json:"buyer_logon_id,omitempty"`

	// CodeType 码类型，如果请求时传入了share_code，将在响应参数返回吱口令；如果为空，则默认为订单码
	//
	// Example: share_code
	CodeType *string `json:"code_type,omitempty"`

	// DisablePayChannels 禁用渠道,用户不可用指定渠道支付，多个渠道以逗号分割	注，与enable_pay_channels互斥	<a href="https://docs.open.alipay.com/common/wifww7">渠道列表</a>
	//
	// Example: pcredit,moneyFund,debitCardExpress
	DisablePayChannels *string `json:"disable_pay_channels,omitempty"`

	// DiscountableAmount 可打折金额。	参与优惠计算的金额，单位为元，精确到小数点后两位，取值范围[0.01,100000000]。 	如果同时传入了【可打折金额】、【不可打折金额】和【订单总金额】，则必须满足如下条件：【订单总金额】=【可打折金额】+【不可打折金额】。	如果订单金额全部参与优惠计算，则【可打折金额】和【不可打折金额】都无需传入。
	//
	// Example: 80.00
	DiscountableAmount *string `json:"discountable_amount,omitempty"`

	// EnablePayChannels 指定支付渠道。	用户只能使用指定的渠道进行支付，多个渠道以逗号分割。	与disable_pay_channels互斥，支持传入的值：<a target="_blank" href="https://docs.open.alipay.com/common/wifww7">渠道列表</a>。	注：如果传入了指定支付渠道，则用户只能用指定内的渠道支付，包括营销渠道也要指定才能使用。该参数可能导致用户支付受限，慎用。
	//
	// Example: pcredit,moneyFund,debitCardExpress
	EnablePayChannels *string       `json:"enable_pay_channels,omitempty"`
	ExtUserInfo       *ExtUserInfo  `json:"ext_user_info,omitempty"`
	ExtendParams      *ExtendParams `json:"extend_params,omitempty"`

	// GoodsDetail 订单包含的商品列表信息.json格式. 其它说明详见：“商品明细说明”
	GoodsDetail *[]GoodsDetail `json:"goods_detail,omitempty"`

	// MerchantOrderNo 商户的原始订单号
	//
	// Example: 20161008001
	MerchantOrderNo *string `json:"merchant_order_no,omitempty"`

	// NotifyUrl 通知地址
	NotifyUrl *string `json:"notify_url,omitempty"`

	// OperatorId 商户操作员编号。
	//
	// Example: yx_001
	OperatorId *string `json:"operator_id,omitempty"`

	// OutTradeNo 商户订单号。	由商家自定义，64个字符以内，仅支持字母、数字、下划线且需保证在商户端不重复。
	//
	// Example: 20150320010101001
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// PassbackParams 公用回传参数。	如果请求时传递了该参数，支付宝会在异步通知时将该参数原样返回。
	//
	// Example: merchantBizType%3d3C%26merchantBizNo%3d2016010101111
	PassbackParams *string `json:"passback_params,omitempty"`

	// PaymentType 指定支付方式	agent_pay：智能体SDK支付方式；
	//
	// Example: agent_pay
	PaymentType *string `json:"payment_type,omitempty"`

	// ProductCode 产品码。	商家和支付宝签约的产品码。 枚举值（点击查看签约情况）：	<a target="_blank" href="https://opensupport.alipay.com/support/codelab/detail/486/487">FACE_TO_FACE_PAYMENT</a>：当面付产品；	默认值为FACE_TO_FACE_PAYMENT。
	//
	// Example: FACE_TO_FACE_PAYMENT
	ProductCode *string `json:"product_code,omitempty"`

	// QrCodeTimeoutExpress 二维码订单相对超时时间。	该笔订单允许的最晚付款时间，逾期将关闭交易，从生成二维码开始计时。 取值范围：1m～15d。m-分钟，h-小时，d-天，1c-当天（1c-当天的情况下，无论交易何时创建，都在0点关闭）。 该参数数值不接受小数点， 如 1.5h，可转换为 90m。	注：二维码最长有效期是2小时，不管该参数传递的值是多少，超过2小时后二维码都将失效不能再进行扫码支付。
	//
	// Example: 90m
	QrCodeTimeoutExpress *string `json:"qr_code_timeout_express,omitempty"`

	// QueryOptions 返回参数选项。 商户通过传递该参数来定制需要额外返回的信息字段，数组格式。包括但不限于：["hyb_amount","enterprise_pay_info"]
	//
	// Example: ["hyb_amount","enterprise_pay_info"]
	QueryOptions *[]string    `json:"query_options,omitempty"`
	RoyaltyInfo  *RoyaltyInfo `json:"royalty_info,omitempty"`

	// SellerId 卖家支付宝用户ID。	当需要指定收款账号时，通过该参数传入，如果该值为空，则默认为商户签约账号对应的支付宝用户ID。	收款账号优先级规则：门店绑定的收款账户>请求传入的seller_id>商户签约账号对应的支付宝用户ID；	注：直付通和机构间联场景下seller_id无需传入或者保持跟pid一致；	如果传入的seller_id与pid不一致，需要联系支付宝小二配置收款关系；
	//
	// Example: 2088102146225135
	SellerId   *string     `json:"seller_id,omitempty"`
	SettleInfo *SettleInfo `json:"settle_info,omitempty"`

	// StoreId 商户门店编号。	指商户创建门店时输入的门店编号。
	//
	// Example: NJ_001
	StoreId     *string      `json:"store_id,omitempty"`
	SubMerchant *SubMerchant `json:"sub_merchant,omitempty"`

	// Subject 订单标题。	注意：不可使用特殊字符，如 /，=，& 等。
	//
	// Example: Iphone6 16G
	Subject *string `json:"subject,omitempty"`

	// TerminalId 商户机具终端编号。
	//
	// Example: NJ_T_001
	TerminalId *string `json:"terminal_id,omitempty"`

	// TimeExpire 订单绝对超时时间。	格式为yyyy-MM-dd HH:mm:ss。	注：time_expire和timeout_express两者只需传入一个或者都不传，如果两者都传，优先使用time_expire。
	//
	// Example: 2021-12-31 10:05:00
	TimeExpire *string `json:"time_expire,omitempty"`

	// TimeoutExpress 订单相对超时时间。 从预下单请求时间开始计算。	该笔订单允许的最晚付款时间，逾期将关闭交易。取值范围：1m～15d。m-分钟，h-小时，d-天，1c-当天（1c-当天的情况下，无论交易何时创建，都在0点关闭）。 该参数数值不接受小数点， 如 1.5h，可转换为 90m。 	当面付场景默认值为3h，如需指定，推荐设置5m及以上		注：	1. 二维码最长有效期是2小时，不管该参数传递的值是多少，超过2小时后二维码都将失效不能再进行扫码支付。	2. time_expire和timeout_express两者只需传入一个或者都不传，如果两者都传，优先使用time_expire。
	//
	// Example: 90m
	TimeoutExpress *string `json:"timeout_express,omitempty"`

	// TotalAmount 订单总金额。	单位为元，精确到小数点后两位，取值范围：[0.01,100000000] 。
	//
	// Example: 88.88
	TotalAmount *string `json:"total_amount,omitempty"`

	// UndiscountableAmount 不可打折金额。	不参与优惠计算的金额，单位为元，精确到小数点后两位，取值范围[0.01,100000000]。 	如果同时传入了【可打折金额】、【不可打折金额】和【订单总金额】，则必须满足如下条件：【订单总金额】=【可打折金额】+【不可打折金额】。	如果订单金额全部参与优惠计算，则【可打折金额】和【不可打折金额】都无需传入。
	//
	// Example: 8.88
	UndiscountableAmount *string `json:"undiscountable_amount,omitempty"`
}

// AlipayTradePrecreateResponseModel defines model for AlipayTradePrecreateResponseModel.
type AlipayTradePrecreateResponseModel struct {
	// OutTradeNo 商户的订单号
	//
	// Example: 6823789339978248
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// PrepayId 预下单ID，后续通过该预下单ID唤起收银台支付
	//
	// Example: MV91dHAucHJlb3JkZXJfMjAyNTA2MDRfMjA4ODg0MTAzMzUzMTQ0OF9YUDE1MjUwNjA0MDU1MDA2MDQzNTAyOTQwMDY5OTJfMzMwNzg2XzQyLTIwNzYxJDgq
	PrepayId *string `json:"prepay_id,omitempty"`

	// QrCode 当前预下单请求生成的二维码码串，有效时间2小时，可以用二维码生成工具根据该码串值生成对应的二维码
	//
	// Example: https://qr.alipay.com/bavh4wjlxf12tper3a
	QrCode *string `json:"qr_code,omitempty"`

	// ShareCode 当前预下单请求生成的吱口令码串，有效时间2小时，可以在支付宝app端访问对应内容
	//
	// Example: chb4n8A94Qc
	ShareCode *string `json:"share_code,omitempty"`
}

// AlipayTradeQueryErrorResponseModel defines model for AlipayTradeQueryErrorResponseModel.
type AlipayTradeQueryErrorResponseModel struct {
	// Code 错误码
	Code AlipayTradeQueryErrorResponseModelCode `json:"code"`

	// Links 解决方案链接
	Links *string `json:"links,omitempty"`

	// Message 错误描述
	Message string `json:"message"`
}

// AlipayTradeQueryErrorResponseModelCode 错误码
type AlipayTradeQueryErrorResponseModelCode string

// AlipayTradeQueryModel defines model for AlipayTradeQueryModel.
type AlipayTradeQueryModel struct {
	// OrgPid 银行间联模式下有用，其它场景请不要使用；
	// 	双联通过该参数指定需要查询的交易所属收单机构的pid;
	//
	// Example: 2088101117952222
	OrgPid *string `json:"org_pid,omitempty"`

	// OutTradeNo 订单支付时传入的商户订单号,和支付宝交易号不能同时为空。
	// 	trade_no,out_trade_no如果同时存在优先取trade_no
	//
	// Example: 20150320010101001
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// QueryOptions 查询选项，商户传入该参数可定制本接口同步响应额外返回的信息字段，数组格式。
	//
	// Example: ["trade_settle_info"]
	QueryOptions *[]string `json:"query_options,omitempty"`

	// TradeNo 支付宝交易号，和商户订单号不能同时为空
	//
	// Example: 2014112611001004680 073956707
	TradeNo *string `json:"trade_no,omitempty"`
}

// AlipayTradeQueryResponseModel defines model for AlipayTradeQueryResponseModel.
type AlipayTradeQueryResponseModel struct {
	// AdditionalStatus 交易附加状态：	SELLER_NOT_RECEIVED（买家已付款，卖家未收款）；
	//
	// Example: SELLER_NOT_RECEIVED
	AdditionalStatus *string `json:"additional_status,omitempty"`

	// AlipayStoreId 支付宝店铺编号
	//
	// Example: 2015040900077001000100001232
	AlipayStoreId *string `json:"alipay_store_id,omitempty"`

	// AlipaySubMerchantId 间连商户在支付宝端的商户编号；	 只在银行间联交易场景下返回该信息；
	//
	// Example: 2088301372182171
	AlipaySubMerchantId *string `json:"alipay_sub_merchant_id,omitempty"`

	// AsyncPayApplyStatus 异步支付受理状态，仅异步支付模式且query_options指定async_pay_info时返回。S：受理成功，支付宝内部会在一定期限内捞起任务推进支付，直到支付成功或超出可重试期限；其它：受理结果未知，可重试查询。
	//
	// Example: S
	AsyncPayApplyStatus *string `json:"async_pay_apply_status,omitempty"`

	// AuthTradePayMode 预授权支付模式，该参数仅在信用预授权支付场景下返回。信用预授权支付：CREDIT_PREAUTH_PAY
	//
	// Example: CREDIT_PREAUTH_PAY
	AuthTradePayMode *string `json:"auth_trade_pay_mode,omitempty"`

	// BizSettleMode 账期结算标识，指已完成支付的订单会进行账期管控，不会实时结算。该参数目前会在使用小程序交易组件场景下返回
	//
	// Example: PERIOD
	BizSettleMode   *string          `json:"biz_settle_mode,omitempty"`
	BkagentRespInfo *BkAgentRespInfo `json:"bkagent_resp_info,omitempty"`

	// Body 订单描述；	只在银行间联交易场景下返回该信息；
	//
	// Example: Iphone6 16G
	Body *string `json:"body,omitempty"`

	// BuyerLogonId 买家支付宝账号
	//
	// Example: 159****5620
	BuyerLogonId *string `json:"buyer_logon_id,omitempty"`

	// BuyerOpenId 买家支付宝用户唯一标识
	//
	// Example: 01501o8f93I3nJAGB1jG4ONxtxV25DCN3Gec3uggnC4CJU0
	BuyerOpenId *string `json:"buyer_open_id,omitempty"`

	// BuyerPayAmount 买家实付金额，单位为元，两位小数。该金额代表该笔交易买家实际支付的金额，不包含商户折扣等金额
	//
	// Example: 8.88
	BuyerPayAmount *string `json:"buyer_pay_amount,omitempty"`

	// BuyerUserId 买家在支付宝的用户id
	//
	// Example: 2088101117955611
	BuyerUserId *string `json:"buyer_user_id,omitempty"`

	// BuyerUserName 买家名称；
	// 	买家为个人用户时为买家姓名，买家为企业用户时为企业名称；
	// 	默认不返回该信息，需与支付宝约定后配置返回；
	//
	// Example: 菜鸟网络有限公司
	BuyerUserName *string `json:"buyer_user_name,omitempty"`

	// BuyerUserType 买家用户类型。CORPORATE:企业用户；PRIVATE:个人用户。
	//
	// Example: PRIVATE
	BuyerUserType *string `json:"buyer_user_type,omitempty"`

	// CashierType 收银台类型。 	用户支付的收银台类型，取值如下： 	APP：支付宝APP收银台支付； 	WAP：支付H5收银台支付； 	注：只有在无线产品支付接口请求中query_options指定cashier_type才返回该字段。
	//
	// Example: APP
	CashierType *string `json:"cashier_type,omitempty"`

	// ChargeAmount 该笔交易针对收款方的收费金额；单位：元。	 只在银行间联交易场景下返回该信息；
	//
	// Example: 8.88
	ChargeAmount *string `json:"charge_amount,omitempty"`

	// ChargeFlags 费率活动标识。	当交易享受特殊行业或活动费率时，返回该场景的标识。具体场景如下：	trade_special_00：订单优惠费率；	industry_special_on_00：线上行业特殊费率0；	industry_special_on_01：线上行业特殊费率1；	industry_special_00：线下行业特殊费率0；	industry_special_01：线下行业特殊费率1；	bluesea_1：蓝海活动优惠费率标签；	注：只在机构间联模式下返回，其它场景下不返回该字段；
	//
	// Example: bluesea_1
	ChargeFlags *string `json:"charge_flags,omitempty"`

	// ChargeInfoList 计费信息列表
	ChargeInfoList *[]ChargeInfo `json:"charge_info_list,omitempty"`

	// CreditBizOrderId 信用业务单号。信用支付场景才有值，先用后付产品里是芝麻订单号。
	//
	// Example: ZMCB99202103310000450000041833
	CreditBizOrderId *string `json:"credit_biz_order_id,omitempty"`

	// CreditPayMode 信用支付模式。表示订单是采用信用支付方式（支付时买家没有出资，需要后续履约）。"creditAdvanceV2"表示芝麻先用后付模式，用户后续需要履约扣款。 此字段只有信用支付场景才有值，商户需要根据字段值单独处理。此字段以后可能扩展其他值，建议商户使用白名单方式识别，对于未识别的值做失败处理，并联系支付宝技术支持人员。
	//
	// Example: creditAdvanceV2
	CreditPayMode *string `json:"credit_pay_mode,omitempty"`

	// DiscountAmount 平台优惠金额。单位：元。
	//
	// Example: 88.88
	DiscountAmount *string `json:"discount_amount,omitempty"`

	// DiscountGoodsDetail 本次交易支付所使用的单品券优惠的商品优惠信息。	只有在query_options中指定时才返回该字段信息。
	//
	// Example: [{"goods_id":"STANDARD1026181538","goods_name":"雪碧","discount_amount":"100.00","voucher_id":"2015102600073002039000002D5O"}]
	DiscountGoodsDetail *string            `json:"discount_goods_detail,omitempty"`
	EnterprisePayInfo   *EnterprisePayInfo `json:"enterprise_pay_info,omitempty"`

	// ExtInfos 交易额外信息，特殊场景下与支付宝约定返回。	json格式。
	//
	// Example: {"action":"cancel"}
	ExtInfos          *string            `json:"ext_infos,omitempty"`
	ExternalPayerInfo *ExternalPayerInfo `json:"external_payer_info,omitempty"`

	// FulfillmentDetailList 履约详情列表。 只有入参的query_options中指定fulfillment_detail_list并且所查询的交易存在履约明细时才返回该字段信息。
	FulfillmentDetailList *[]FulfillmentDetail `json:"fulfillment_detail_list,omitempty"`

	// FundBillList 交易支付使用的资金渠道。	只有在签约中指定需要返回资金明细，或者入参的query_options中指定时才返回该字段信息。
	FundBillList *[]TradeFundBill `json:"fund_bill_list,omitempty"`
	HbFqPayInfo  *HbFqPayInfo     `json:"hb_fq_pay_info,omitempty"`

	// HybAmount 惠营宝回票金额。单位：元。
	//
	// Example: 10.24
	HybAmount *string `json:"hyb_amount,omitempty"`

	// IndustrySepcDetail 行业特殊信息（例如在医保卡支付业务中，向用户返回医疗信息）。
	//
	// Example: {"registration_order_pay":{"brlx":"1","cblx":"1"}}
	IndustrySepcDetail *string `json:"industry_sepc_detail,omitempty"`

	// IndustrySepcDetailAcc 行业特殊信息-个账相关
	//
	// Example: {"registration_order_pay":{"brlx":"1","cblx":"1"}}
	IndustrySepcDetailAcc *string `json:"industry_sepc_detail_acc,omitempty"`

	// IndustrySepcDetailGov 行业特殊信息-统筹相关
	//
	// Example: {"registration_order_pay":{"brlx":"1","cblx":"1"}}
	IndustrySepcDetailGov *string `json:"industry_sepc_detail_gov,omitempty"`

	// IntactChargeInfoList 完整的收费信息
	IntactChargeInfoList *[]IntactChargeInfo `json:"intact_charge_info_list,omitempty"`

	// InvoiceAmount 交易中用户支付的可开具发票的金额，单位为元，两位小数。该金额代表该笔交易中可以给用户开具发票的金额
	//
	// Example: 12.11
	InvoiceAmount *string `json:"invoice_amount,omitempty"`

	// MdiscountAmount 商家优惠金额。单位：元。
	//
	// Example: 88.88
	MdiscountAmount *string `json:"mdiscount_amount,omitempty"`

	// MedicalInsuranceInfo 医保信息。入参的query_options中指定时才返回该字段信息。medicareCardType：医保卡类型，"1":"亲情支付","0":"本人支付"，为空默认为本人支付；medicareCardHolderHiddenName：医保卡持卡人姓名。
	//
	// Example: "{\"medicareCardType\":\"1\",\"medicareCardHolderHiddenName\":\"**华\"}"
	MedicalInsuranceInfo *string `json:"medical_insurance_info,omitempty"`

	// OpenId 买家支付宝用户号，该字段将废弃，不要使用
	//
	// Example: 2088102122524333
	OpenId *string `json:"open_id,omitempty"`

	// OutTradeNo 商家订单号
	//
	// Example: 6823789339978248
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// PassbackParams 公用回传参数。	返回支付时传入的passback_params参数信息
	//
	// Example: merchantBizType%3d3C%26merchantBizNo%3d2016010101111
	PassbackParams *string `json:"passback_params,omitempty"`

	// PayAmount 支付币种订单金额
	//
	// Example: 8.88
	PayAmount *string `json:"pay_amount,omitempty"`

	// PayCurrency 订单支付币种
	//
	// Example: CNY
	PayCurrency *string `json:"pay_currency,omitempty"`

	// PaymentInfoWithIdList 带支付宝支付id的信息，暂不对外开放
	PaymentInfoWithIdList *[]PaymentInfoWithId `json:"payment_info_with_id_list,omitempty"`

	// PeriodScene 该字段用于描述当前账期交易的场景。
	//
	// Example: 账期交易的场景。
	PeriodScene *string `json:"period_scene,omitempty"`

	// PointAmount 积分支付的金额，单位为元，两位小数。该金额代表该笔交易中用户使用积分支付的金额，比如集分宝或者支付宝实时优惠等
	//
	// Example: 10
	PointAmount *string `json:"point_amount,omitempty"`

	// PreAuthPayAmount 当用户使用芝麻信用先享后付时，会返回该字段，代表整笔交易的原始待履约金额，单位元。
	//
	// Example: 12.46
	PreAuthPayAmount *string `json:"pre_auth_pay_amount,omitempty"`

	// PurchaseEntity 支付宝钱包跨境支付交易的购汇主体，ALIPAYHK-境外香港购汇实体，3008境内购汇实体
	//
	// Example: 3008
	PurchaseEntity *string `json:"purchase_entity,omitempty"`

	// ReceiptAmount 实收金额，单位为元，两位小数。该金额为本笔交易，商户账户能够实际收到的金额
	//
	// Example: 15.25
	ReceiptAmount *string `json:"receipt_amount,omitempty"`

	// ReceiptCurrencyType 收款资金类型，当交易收款资金为数字人民币时返回值为“DC”，否则不返回该字段。
	//
	// Example: DC
	ReceiptCurrencyType *string `json:"receipt_currency_type,omitempty"`

	// ReqGoodsDetail 支付请求的商品明细列表
	ReqGoodsDetail *[]GoodsDetail `json:"req_goods_detail,omitempty"`

	// SendPayDate 本次交易打款给卖家的时间
	//
	// Example: 2014-11-27 15:45:57
	SendPayDate *string `json:"send_pay_date,omitempty"`

	// SettleAmount 结算币种订单金额
	//
	// Example: 2.96
	SettleAmount *string `json:"settle_amount,omitempty"`

	// SettleCurrency 订单结算币种，对应支付接口传入的settle_currency，支持英镑：GBP、港币：HKD、美元：USD、新加坡元：SGD、日元：JPY、加拿大元：CAD、澳元：AUD、欧元：EUR、新西兰元：NZD、韩元：KRW、泰铢：THB、瑞士法郎：CHF、瑞典克朗：SEK、丹麦克朗：DKK、挪威克朗：NOK、马来西亚林吉特：MYR、印尼卢比：IDR、菲律宾比索：PHP、毛里求斯卢比：MUR、以色列新谢克尔：ILS、斯里兰卡卢比：LKR、俄罗斯卢布：RUB、阿联酋迪拉姆：AED、捷克克朗：CZK、南非兰特：ZAR
	//
	// Example: USD
	SettleCurrency *string `json:"settle_currency,omitempty"`

	// SettleTransRate 结算币种兑换标价币种汇率
	//
	// Example: 30.025
	SettleTransRate *string `json:"settle_trans_rate,omitempty"`

	// SettlementId 支付清算编号，用于清算对账使用；
	// 	只在银行间联交易场景下返回该信息；
	//
	// Example: 2018101610032004620239146945
	SettlementId *string `json:"settlement_id,omitempty"`

	// StoreId 商户门店编号
	//
	// Example: NJ_S_001
	StoreId *string `json:"store_id,omitempty"`

	// StoreName 请求交易支付中的商户店铺的名称
	//
	// Example: 证大五道口店
	StoreName *string `json:"store_name,omitempty"`

	// Subject 订单标题；	 只在银行间联交易场景下返回该信息；
	//
	// Example: Iphone6 16G
	Subject    *string     `json:"subject,omitempty"`
	TapPayInfo *TapPayInfo `json:"tap_pay_info,omitempty"`

	// TerminalId 商户机具终端编号
	//
	// Example: NJ_T_001
	TerminalId *string `json:"terminal_id,omitempty"`

	// TotalAmount 交易的订单金额，单位为元，两位小数。该参数的值为支付时传入的total_amount
	//
	// Example: 88.88
	TotalAmount *string `json:"total_amount,omitempty"`

	// TradeNo 支付宝交易号
	//
	// Example: 2013112011001004330000121536
	TradeNo         *string          `json:"trade_no,omitempty"`
	TradeSettleInfo *TradeSettleInfo `json:"trade_settle_info,omitempty"`

	// TradeStatus 交易状态：WAIT_BUYER_PAY（交易创建，等待买家付款）、TRADE_CLOSED（未付款交易超时关闭，或支付完成后全额退款）、TRADE_SUCCESS（交易支付成功）、TRADE_FINISHED（交易结束，不可退款）
	//
	// Example: TRADE_CLOSED
	TradeStatus *string `json:"trade_status,omitempty"`

	// TransCurrency 标价币种，该参数的值为支付时传入的trans_currency，支持英镑：GBP、港币：HKD、美元：USD、新加坡元：SGD、日元：JPY、加拿大元：CAD、澳元：AUD、欧元：EUR、新西兰元：NZD、韩元：KRW、泰铢：THB、瑞士法郎：CHF、瑞典克朗：SEK、丹麦克朗：DKK、挪威克朗：NOK、马来西亚林吉特：MYR、印尼卢比：IDR、菲律宾比索：PHP、毛里求斯卢比：MUR、以色列新谢克尔：ILS、斯里兰卡卢比：LKR、俄罗斯卢布：RUB、阿联酋迪拉姆：AED、捷克克朗：CZK、南非兰特：ZAR、人民币：CNY、新台币：TWD。当trans_currency 和 settle_currency 不一致时，trans_currency支持人民币：CNY、新台币：TWD
	//
	// Example: TWD
	TransCurrency *string `json:"trans_currency,omitempty"`

	// TransPayRate 标价币种兑换支付币种汇率
	//
	// Example: 0.264
	TransPayRate *string `json:"trans_pay_rate,omitempty"`

	// UnpaidReason 有限条件下返回当前订单未支付原因
	//
	// Example: 其他原因
	UnpaidReason *string `json:"unpaid_reason,omitempty"`

	// VoucherDetailList 本交易支付时使用的所有优惠券信息。	只有在query_options中指定时才返回该字段信息。
	VoucherDetailList *[]VoucherDetail `json:"voucher_detail_list,omitempty"`
}

// AlipayTradeRefundErrorResponseModel defines model for AlipayTradeRefundErrorResponseModel.
type AlipayTradeRefundErrorResponseModel struct {
	// Code 错误码
	Code AlipayTradeRefundErrorResponseModelCode `json:"code"`

	// Links 解决方案链接
	Links *string `json:"links,omitempty"`

	// Message 错误描述
	Message string `json:"message"`
}

// AlipayTradeRefundErrorResponseModelCode 错误码
type AlipayTradeRefundErrorResponseModelCode string

// AlipayTradeRefundModel defines model for AlipayTradeRefundModel.
type AlipayTradeRefundModel struct {
	// GoodsDetail 退款包含的商品列表信息，Json格式。
	GoodsDetail *[]GoodsDetail `json:"goods_detail,omitempty"`

	// OperatorId 商户的操作员编号
	//
	// Example: OP001
	OperatorId *string `json:"operator_id,omitempty"`

	// OrgPid 银行间联模式下有用，其它场景请不要使用；
	// 	双联通过该参数指定需要退款的交易所属收单机构的pid;
	//
	// Example: 2088101117952222
	OrgPid *string `json:"org_pid,omitempty"`

	// OutRequestNo 退款请求号。	标识一次退款请求，需要保证在交易号下唯一，如需部分退款，则此参数必传。	注：针对同一次退款请求，如果调用接口失败或异常了，重试时需要保证退款请求号不能变更，防止该笔交易重复退款。支付宝会保证同样的退款请求号多次请求只会退一次。
	//
	// Example: HZ01RF001
	OutRequestNo *string `json:"out_request_no,omitempty"`

	// OutTradeNo 商户订单号。	订单支付时传入的商户订单号，商家自定义且保证商家系统中唯一。与支付宝交易号 trade_no 不能同时为空。
	//
	// Example: 20150320010101001
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// QueryOptions 查询选项。	商户通过上送该参数来定制同步需要额外返回的信息字段，数组格式。
	//
	// Example: ["refund_detail_item_list"]
	QueryOptions *[]string `json:"query_options,omitempty"`

	// RefundAdvanceAccount 指定垫资退款账号主体，可能是用户id或登录名
	//
	// Example: loginname@alitest.com
	RefundAdvanceAccount *string `json:"refund_advance_account,omitempty"`

	// RefundAdvanceAccountType 指定垫资退款账号的类型，取值范围：default，userId，loginName
	//
	// Example: loginName
	RefundAdvanceAccountType *string `json:"refund_advance_account_type,omitempty"`

	// RefundAmount 退款金额。	需要退款的金额，该金额不能大于订单金额，单位为元，支持两位小数。	注：如果正向交易使用了营销，该退款金额包含营销金额，支付宝会按业务规则分配营销和买家自有资金分别退多少，默认优先退买家的自有资金。如交易总金额100元，用户支付时使用了80元自有资金和20元无资金流的营销券，商家实际收款80元。如果首次请求退款60元，则60元全部从商家收款资金扣除退回给用户自有资产；如果再请求退款40元，则从商家收款资金扣除20元退回用户资产以及把20元的营销券退回给用户（券是否可再使用取决于券的规则配置）。
	//
	// Example: 200.12
	RefundAmount *string `json:"refund_amount,omitempty"`

	// RefundCurrency 订单退款币种信息。支持英镑：GBP、港币：HKD、美元：USD、新加坡元：SGD、日元：JPY、加拿大元：CAD、澳元：AUD、欧元：EUR、新西兰元：NZD、韩元：KRW、泰铢：THB、瑞士法郎：CHF、瑞典克朗：SEK、丹麦克朗：DKK、挪威克朗：NOK、马来西亚林吉特：MYR、印尼卢比：IDR、菲律宾比索：PHP、毛里求斯卢比：MUR、以色列新谢克尔：ILS、斯里兰卡卢比：LKR、俄罗斯卢布：RUB、阿联酋迪拉姆：AED、捷克克朗：CZK、南非兰特：ZAR、人民币：CNY
	//
	// Example: USD
	RefundCurrency *string `json:"refund_currency,omitempty"`

	// RefundGoodsDetail 退款包含的商品列表信息
	RefundGoodsDetail *[]RefundGoodsDetail `json:"refund_goods_detail,omitempty"`

	// RefundReason 退款原因说明。	商家自定义，将在会在商户和用户的pc退款账单详情中展示
	//
	// Example: 正常退款
	RefundReason *string `json:"refund_reason,omitempty"`

	// RefundRoyaltyParameters 退分账明细信息。	 注： 1.当面付且非直付通模式无需传入退分账明细，系统自动按退款金额与订单金额的比率，从收款方和分账收入方退款，不支持指定退款金额与退款方。 	2.直付通模式，电脑网站支付，手机 APP 支付，手机网站支付产品，须在退款请求中明确是否退分账，从哪个分账收入方退，退多少分账金额；如不明确，默认从收款方退款，收款方余额不足退款失败。不支持系统按比率退款。
	RefundRoyaltyParameters *[]OpenApiRoyaltyDetailInfoPojo `json:"refund_royalty_parameters,omitempty"`

	// RefundTransOut 指定退款账号，对应指定账号退款合约中的约定账号		与refund_trans_out_type绑定使用	1、refund_trans_out_type=userId时，传入对应的支付宝2088账号	2、refund_trans_out_type=loginName时，传入对应的支付宝账号登录名
	//
	// Example: 2088xxxxxxxxxxxx
	RefundTransOut *string `json:"refund_trans_out,omitempty"`

	// RefundTransOutType 指定退款账号类型	userId：支付宝账号id	loginName：支付宝账号登录名
	//
	// Example: userId
	RefundTransOutType *string `json:"refund_trans_out_type,omitempty"`

	// RelatedSettleConfirmNo 针对账期交易，在确认结算后退款的话，需要指定确认结算时的结算单号。
	//
	// Example: 2024041122001495000530302869
	RelatedSettleConfirmNo *string `json:"related_settle_confirm_no,omitempty"`

	// StoreId 商户门店编号，由商家自定义。需保证当前商户下唯一。
	//
	// Example: NJ_S_001
	StoreId *string `json:"store_id,omitempty"`

	// TerminalId 商户的终端编号
	//
	// Example: NJ_T_001
	TerminalId *string `json:"terminal_id,omitempty"`

	// TradeNo 支付宝交易号。	和商户订单号 out_trade_no 不能同时为空，两者同时存在时，优先取值trade_no
	//
	// Example: 2014112611001004680073956707
	TradeNo *string `json:"trade_no,omitempty"`
}

// AlipayTradeRefundResponseModel defines model for AlipayTradeRefundResponseModel.
type AlipayTradeRefundResponseModel struct {
	// BuyerLogonId 用户的登录id
	//
	// Example: 159****5620
	BuyerLogonId *string `json:"buyer_logon_id,omitempty"`

	// BuyerOpenId 买家支付宝用户唯一标识
	//
	// Example: 074a1CcTG1LelxKe4xQC0zgNdId0nxi95b5lsNpazWYoCo5
	BuyerOpenId *string `json:"buyer_open_id,omitempty"`

	// BuyerUserId 买家在支付宝的用户id
	//
	// Example: 2088101117955611
	BuyerUserId *string `json:"buyer_user_id,omitempty"`

	// FundChange 本次退款是否发生了资金变化
	//
	// Example: Y
	FundChange *string `json:"fund_change,omitempty"`

	// GmtRefundPay 退款支付时间
	//
	// Example: 2014-11-27 15:45:57
	GmtRefundPay *string `json:"gmt_refund_pay,omitempty"`

	// HasDepositBack 是否有银行卡冲退，仅当query_options中传入deposit_back_info时返回
	//
	// Example: true
	HasDepositBack *string `json:"has_deposit_back,omitempty"`

	// OpenId 买家支付宝用户号，该参数已废弃，请不要使用
	//
	// Example: 2088102122524333
	OpenId *string `json:"open_id,omitempty"`

	// OutTradeNo 商户订单号
	//
	// Example: 6823789339978248
	OutTradeNo *string `json:"out_trade_no,omitempty"`

	// PreAuthCancelFee 当用户使用芝麻信用先享后付时，且当前的操作为预授权撤销动作时，会返回该字段，代表当前撤销的预授权金额，单位元。
	//
	// Example: 12.45
	PreAuthCancelFee *string `json:"pre_auth_cancel_fee,omitempty"`

	// PresentRefundBuyerAmount 本次退款金额中买家退款金额;单位：元。	该字段默认不返回；
	//
	// Example: 88.88
	PresentRefundBuyerAmount *string `json:"present_refund_buyer_amount,omitempty"`

	// PresentRefundDiscountAmount 本次退款金额中平台优惠退款金额；单位：元。	该字段默认不返回；
	//
	// Example: 88.88
	PresentRefundDiscountAmount *string `json:"present_refund_discount_amount,omitempty"`

	// PresentRefundMdiscountAmount 本次退款金额中商家优惠退款金额；单位：元。	该字段默认不返回；
	//
	// Example: 88.88
	PresentRefundMdiscountAmount *string `json:"present_refund_mdiscount_amount,omitempty"`

	// RefundChargeAmount 本次退款针对收款方的退收费金额；单位：元。	只在机构间联模式下返回，其它场景下不返回该字段；
	//
	// Example: 8.88
	RefundChargeAmount *string `json:"refund_charge_amount,omitempty"`

	// RefundChargeInfoList 退费信息
	RefundChargeInfoList *[]RefundChargeInfo `json:"refund_charge_info_list,omitempty"`

	// RefundCurrency 退款币种信息
	//
	// Example: USD
	RefundCurrency *string `json:"refund_currency,omitempty"`

	// RefundDetailItemList 退款使用的资金渠道。	只有在签约中指定需要返回资金明细，或者入参的query_options中指定时才返回该字段信息。
	RefundDetailItemList *[]TradeFundBill `json:"refund_detail_item_list,omitempty"`

	// RefundFee 退款总金额。单位：元。	指该笔交易累计已经退款成功的金额。
	//
	// Example: 88.88
	RefundFee *string `json:"refund_fee,omitempty"`

	// RefundHybAmount 本次请求退惠营宝金额。单位：元。
	//
	// Example: 10.24
	RefundHybAmount         *string            `json:"refund_hyb_amount,omitempty"`
	RefundPresetPaytoolList *PresetPayToolInfo `json:"refund_preset_paytool_list,omitempty"`

	// RefundSettlementId 退款清算编号，用于清算对账使用；	只在机构间联模式下返回，其它场景下不返回该字段；
	//
	// Example: 2018101610032004620239146945
	RefundSettlementId *string `json:"refund_settlement_id,omitempty"`

	// RefundVoucherDetailList 本交易支付时使用的所有优惠券信息。 只有在query_options中指定了refund_voucher_detail_list时才返回该字段信息。
	RefundVoucherDetailList *[]VoucherDetail `json:"refund_voucher_detail_list,omitempty"`

	// SendBackFee 本次商户实际退回金额。单位：元。	说明：如需获取该值，需在入参query_options中传入 refund_detail_item_list。
	//
	// Example: 1.8
	SendBackFee *string `json:"send_back_fee,omitempty"`

	// StoreName 交易在支付时候的门店名称
	//
	// Example: 望湘园联洋店
	StoreName *string `json:"store_name,omitempty"`

	// TradeNo 支付宝交易号
	//
	// Example: 2013112011001004330000121536
	TradeNo *string `json:"trade_no,omitempty"`
}

// BkAgentReqInfo defines model for BkAgentReqInfo.
type BkAgentReqInfo struct {
	// AcqCode 收单机构在清算组织登记或分配的机构代码
	AcqCode *string `json:"acq_code,omitempty"`

	// DeviceType 终端设备类型，受理方可参考终端注册时的设备类型填写。
	DeviceType *string `json:"device_type,omitempty"`

	// Location 终端设备实时经纬度信息，格式为纬度/经度，+表示北纬、东经，-表示南纬、西经。
	Location *string `json:"location,omitempty"`

	// MerchCode 收单机构在清算组织登记的商户编码
	MerchCode *string `json:"merch_code,omitempty"`

	// SerialNum 终端类型填写为 02、	03、04、05、06、08、09 或 10 时，必	须填写终端序列号。
	SerialNum *string `json:"serial_num,omitempty"`
}

// BkAgentRespInfo defines model for BkAgentRespInfo.
type BkAgentRespInfo struct {
	// BindclrissrId 枚举值，01 银联；02 网联；03 连通等
	BindclrissrId *string `json:"bindclrissr_id,omitempty"`

	// BindpyeracctbkId 付款机构在清算组织登记或分配的机构代码
	BindpyeracctbkId *string `json:"bindpyeracctbk_id,omitempty"`

	// BindtrxId 原快捷交易流水号
	BindtrxId *string `json:"bindtrx_id,omitempty"`

	// BkpyeruserCode 用户在银行付款账号的标记化处理编号
	BkpyeruserCode *string `json:"bkpyeruser_code,omitempty"`

	// EstterLocation 设备推测位置
	EstterLocation *string `json:"estter_location,omitempty"`
}

// BusinessParams defines model for BusinessParams.
type BusinessParams struct {
	// ActualOrderTime 实际订单时间，在乘车码场景，传入的是用户刷码乘车时间
	ActualOrderTime *string `json:"actual_order_time,omitempty"`

	// BuyerMemo 买家备注信息
	BuyerMemo *string `json:"buyer_memo,omitempty"`

	// CampusCard 校园卡编号
	CampusCard *string `json:"campus_card,omitempty"`

	// CardType 虚拟卡卡类型
	CardType *string `json:"card_type,omitempty"`

	// EnterprisePayAmount 因公付金额，单位：元。
	EnterprisePayAmount *string `json:"enterprise_pay_amount,omitempty"`

	// EnterprisePayInfo 因公付业务信息
	EnterprisePayInfo *string `json:"enterprise_pay_info,omitempty"`

	// ForcePwd 收银台强制密码核身参数，实际收银侧会根据这个参数为true并结合业务场景来判断是否密码核身
	ForcePwd *string `json:"force_pwd,omitempty"`

	// GoodTaxes 商户传入的交易税费。需要落地风控使用
	GoodTaxes *string `json:"good_taxes,omitempty"`

	// McCreateTradeIp 商户端创建订单的 IP，须上传正确的用户端外网 IP，支持 ipv4/ipv6 格式；	mc_create_trade_ip和mcCreateTradeIp（旧）参数描述相同，首选mc_create_trade_ip入参，请勿重复入参；	如已入参mcCreateTradeIp（旧），无需新增入参mc_create_trade_ip。
	McCreateTradeIp *string `json:"mc_create_trade_ip,omitempty"`

	// PriorityUnfreezeAsset 信用预授权转交易阶段，优先解冻的用户资产	CREDIT_ASSET：信用资产	COMMON_ASSET：自有资金资产	默认优先解冻资金资产
	PriorityUnfreezeAsset *string `json:"priority_unfreeze_asset,omitempty"`

	// TinyAppMerchantBizType 当需要在 商家平台（b.alipay.com）—数据中心 中查看对应业务场景下的数据明细可以通过该参数传入	支持传入的值：<a target="_blank" href="https://opendocs.alipay.com/mini/08by8k?pathHash=96e03412">小程序细分业务场景</a>
	TinyAppMerchantBizType *string `json:"tiny_app_merchant_biz_type,omitempty"`
}

// ChargeInfo defines model for ChargeInfo.
type ChargeInfo struct {
	// ChargeFee 实收费用
	ChargeFee *string `json:"charge_fee,omitempty"`

	// ChargeType 收单手续费trade，花呗分期手续hbfq，其他手续费charge
	ChargeType *string `json:"charge_type,omitempty"`

	// IsRatingOnSwitch 是否合约指定收费账号出资，值为"Y"或"N"
	IsRatingOnSwitch *string `json:"is_rating_on_switch,omitempty"`

	// IsRatingOnTradeReceiver 是否收款账号出资，值为"Y"或"N"
	IsRatingOnTradeReceiver *string `json:"is_rating_on_trade_receiver,omitempty"`

	// OriginalChargeFee 原始费用
	OriginalChargeFee *string `json:"original_charge_fee,omitempty"`

	// SubFeeDetailList 组合支付收费明细
	SubFeeDetailList *[]SubFee `json:"sub_fee_detail_list,omitempty"`

	// SwitchFeeRate 签约费率
	SwitchFeeRate *string `json:"switch_fee_rate,omitempty"`
}

// CloseExtendParams defines model for CloseExtendParams.
type CloseExtendParams struct {
	// IsFulfilled 标识是否通过其他方式履约
	//
	// Example: true or false
	IsFulfilled *string `json:"is_fulfilled,omitempty"`
}

// CommonErrorType defines model for CommonErrorType.
type CommonErrorType struct {
	// Code 错误码
	Code CommonErrorTypeCode `json:"code"`

	// Links 解决方案链接
	Links *string `json:"links,omitempty"`

	// Message 错误描述
	Message string `json:"message"`
}

// CommonErrorTypeCode 错误码
type CommonErrorTypeCode string

// ContributeDetail defines model for ContributeDetail.
type ContributeDetail struct {
	// ContributeAmount 出资方金额
	ContributeAmount *string `json:"contribute_amount,omitempty"`

	// ContributeType 出资方类型
	ContributeType *string `json:"contribute_type,omitempty"`
}

// DepositBackInfo defines model for DepositBackInfo.
type DepositBackInfo struct {
	// BankAckTime 银行响应时间，格式为yyyy-MM-dd HH:mm:ss
	BankAckTime *string `json:"bank_ack_time,omitempty"`

	// DbackAmount 银行卡冲退金额。单位：元。
	DbackAmount *string `json:"dback_amount,omitempty"`

	// DbackStatus 银行卡冲退状态。S-成功，F-失败，P-处理中。银行卡冲退失败，资金自动转入用户支付宝余额。
	DbackStatus *string `json:"dback_status,omitempty"`

	// EstBankReceiptTime 预估银行到账时间，格式为yyyy-MM-dd HH:mm:ss
	EstBankReceiptTime *string `json:"est_bank_receipt_time,omitempty"`

	// HasDepositBack 是否存在银行卡冲退信息。
	HasDepositBack *string `json:"has_deposit_back,omitempty"`
}

// EnterprisePayInfo defines model for EnterprisePayInfo.
type EnterprisePayInfo struct {
	// BizInfo 因公付业务信息
	BizInfo *string `json:"biz_info,omitempty"`

	// InvoiceAmount 开票金额
	InvoiceAmount *string `json:"invoice_amount,omitempty"`

	// IsUseEnterprisePay 是否包含因公付资产
	IsUseEnterprisePay *bool `json:"is_use_enterprise_pay,omitempty"`
}

// ExtUserInfo defines model for ExtUserInfo.
type ExtUserInfo struct {
	// CertNo 买家证件号。	注：need_check_info=T或fix_buyer=T时该参数才有效，支付宝会比较买家在支付宝留存的证件号码与该参数传入的值是否匹配。
	CertNo *string `json:"cert_no,omitempty"`

	// CertType 指定买家证件类型。	枚举值：	IDENTITY_CARD：身份证；	PASSPORT：护照；	OFFICER_CARD：军官证；	SOLDIER_CARD：士兵证；	HOKOU：户口本；	PERMANENT_RESIDENCE_FOREIGNER：外国人永久居留身份证。	如有其它类型需要支持，请与蚂蚁金服工作人员联系。	注： need_check_info=T或fix_buyer=T时该参数才有效，支付宝会比较买家在支付宝留存的证件类型与该参数传入的值是否匹配。
	CertType *string `json:"cert_type,omitempty"`

	// FixBuyer 是否强制校验买家身份。	需要强制校验传：T;	不需要强制校验传：F或者不传；	当传T时，接口上必须指定cert_type、cert_no和name信息且支付宝会校验传入的信息跟支付买家的信息都匹配，否则报错。	默认为不校验。
	FixBuyer *string `json:"fix_buyer,omitempty"`

	// IdentityHash 买家加密身份信息。当指定了此参数且指定need_check_info=T时，支付宝会对买家身份进行校验，校验逻辑为买家姓名、买家证件号拼接后的字符串，以sha256算法utf-8编码计算hash，若与传入的值不匹配则会拦截本次支付。注意：如果同时指定了用户明文身份信息（name，cert_type，cert_no中任意一个），则忽略identity_hash以明文参数校验。
	IdentityHash *string `json:"identity_hash,omitempty"`

	// MinAge 允许的最小买家年龄。	买家年龄必须大于等于所传数值 	注：	1. need_check_info=T时该参数才有效	2. min_age为整数，必须大于等于0
	MinAge *string `json:"min_age,omitempty"`

	// Mobile 指定买家手机号。	注：该参数暂不校验
	Mobile *string `json:"mobile,omitempty"`

	// Name 指定买家姓名。	注： need_check_info=T或fix_buyer=T时该参数才有效
	Name *string `json:"name,omitempty"`

	// NeedCheckInfo 是否强制校验买家信息；	需要强制校验传：T;	不需要强制校验传：F或者不传；	当传T时，支付宝会校验支付买家的信息与接口上传递的cert_type、cert_no、name或age是否匹配，只有接口传递了信息才会进行对应项的校验；只要有任何一项信息校验不匹配交易都会失败。如果传递了need_check_info，但是没有传任何校验项，则不进行任何校验。	默认为不校验。
	NeedCheckInfo *string `json:"need_check_info,omitempty"`
}

// ExtendParams defines model for ExtendParams.
type ExtendParams struct {
	// CardType 卡类型
	CardType *string `json:"card_type,omitempty"`

	// CreditExtInfo 信用参数，可选，如有需要请与芝麻约定后传入，信用服务说明见
	CreditExtInfo *string `json:"credit_ext_info,omitempty"`

	// HbFqNum 使用花呗分期要进行的分期数
	HbFqNum *string `json:"hb_fq_num,omitempty"`

	// HbFqSellerPercent 使用花呗分期需要卖家承担的手续费比例的百分值，传入100代表100%
	HbFqSellerPercent *string `json:"hb_fq_seller_percent,omitempty"`

	// IndustryRefluxInfo 行业数据回流信息, 详见：地铁支付接口参数补充说明
	IndustryRefluxInfo *string `json:"industry_reflux_info,omitempty"`

	// RoyaltyFreeze 是否进行资金冻结，用于后续分账，true表示资金冻结，false或不传表示资金不冻结
	RoyaltyFreeze *string `json:"royalty_freeze,omitempty"`

	// SpecifiedSellerName 特殊场景下，允许商户指定交易展示的卖家名称
	SpecifiedSellerName *string `json:"specified_seller_name,omitempty"`

	// SysServiceProviderId 系统商编号
	// 	该参数作为系统商返佣数据提取的依据，请填写系统商签约协议的PID
	SysServiceProviderId *string `json:"sys_service_provider_id,omitempty"`

	// TcInstallmentOrderId 公域商品交易分期单ID，小程序交易组件订单特殊场景使用，请传入 订单分期接口(alipay.open.mini.order.installment.create)中返回的installment_order_id
	TcInstallmentOrderId *string `json:"tc_installment_order_id,omitempty"`

	// TradeComponentOrderId 公域商品交易业务订单ID
	TradeComponentOrderId *string `json:"trade_component_order_id,omitempty"`
}

// ExternalPayerInfo defines model for ExternalPayerInfo.
type ExternalPayerInfo struct {
	// OutInstCardNo 机构卡信息
	//
	// Example: 622221***0898
	OutInstCardNo *string `json:"out_inst_card_no,omitempty"`

	// OutInstPayerInstId 机构编码
	//
	// Example: COMM
	OutInstPayerInstId *string `json:"out_inst_payer_inst_id,omitempty"`

	// OutPayerAccountName 代理企业支付中，企业的名称
	//
	// Example: 支付宝中国有限公司
	OutPayerAccountName *string `json:"out_payer_account_name,omitempty"`
}

// FulfillmentDetail defines model for FulfillmentDetail.
type FulfillmentDetail struct {
	// FulfillmentAmount 履约金额
	//
	// Example: 80.00
	FulfillmentAmount *string `json:"fulfillment_amount,omitempty"`

	// GmtPayment 履约支付时间
	//
	// Example: 2021-03-17 09:45:57
	GmtPayment *string `json:"gmt_payment,omitempty"`

	// OutRequestNo 商户发起履约请求时，传入的out_request_no，标识一次请求的唯一id
	//
	// Example: 20200320010101001
	OutRequestNo *string `json:"out_request_no,omitempty"`
}

// GoodsDetail defines model for GoodsDetail.
type GoodsDetail struct {
	// AlipayGoodsId 支付宝定义的统一商品编号
	AlipayGoodsId *string `json:"alipay_goods_id,omitempty"`

	// Body 商品描述信息
	Body *string `json:"body,omitempty"`

	// CategoriesTree 商品类目树，从商品类目根节点到叶子节点的类目id组成，类目id值使用|分割
	CategoriesTree *string `json:"categories_tree,omitempty"`

	// GoodsCategory 商品类目
	GoodsCategory *string `json:"goods_category,omitempty"`

	// GoodsEanId 商品69条码
	GoodsEanId *string `json:"goods_ean_id,omitempty"`

	// GoodsId 商品的编号，该参数传入支付券上绑定商品goods_id,	倘若无支付券需要消费，该字段传入商品最小粒度的商品ID（如：若商品有sku粒度，则传商户sku粒度的ID）
	GoodsId *string `json:"goods_id,omitempty"`

	// GoodsName 商品名称
	GoodsName *string `json:"goods_name,omitempty"`

	// OutItemId 商家侧小程序商品ID，指商家提报给小程序商品库的商品。当前接口的extend_params.trade_component_order_id字段不为空时该字段必填，且与交易组件订单参数保持一致。了解小程序商品请参考：<a href="https://opendocs.alipay.com/mini/06uila?pathHash=63b6fba7">https://opendocs.alipay.com/mini/06uila?pathHash=63b6fba7</a>
	OutItemId *string `json:"out_item_id,omitempty"`

	// OutSkuId 商家侧小程序商品ID，指商家提报给小程序商品库的商品。当前接口的extend_params.trade_component_order_id字段不为空时该字段必填，且与交易组件订单参数保持一致。了解小程序商品请参考：<a target="_blank" href="https://opendocs.alipay.com/mini/06uila?pathHash=63b6fba7" >https://opendocs.alipay.com/mini/06uila?pathHash=63b6fba7</a>
	OutSkuId *string `json:"out_sku_id,omitempty"`

	// Price 商品单价，单位为元
	Price *string `json:"price,omitempty"`

	// Quantity 商品数量
	Quantity *int `json:"quantity,omitempty"`

	// ShowUrl 商品的展示地址
	ShowUrl *string `json:"show_url,omitempty"`
}

// HbFqPayInfo defines model for HbFqPayInfo.
type HbFqPayInfo struct {
	// FqAmount 用户使用花呗分期支付的金额数。单位：元。
	//
	// Example: 10.05
	FqAmount *string `json:"fq_amount,omitempty"`

	// FqInstId 提供分期服务的机构ID
	//
	// Example: ALIPAY
	FqInstId *string `json:"fq_inst_id,omitempty"`

	// UserInstallNum 用户使用花呗分期支付的分期数
	//
	// Example: 3
	UserInstallNum *string `json:"user_install_num,omitempty"`
}

// IntactChargeInfo defines model for IntactChargeInfo.
type IntactChargeInfo struct {
	// ActualAmount 实际收费金额，单位元
	//
	// Example: 0.01
	ActualAmount *string `json:"actual_amount,omitempty"`

	// BillType 收费类型
	//
	// Example: 1
	BillType *string `json:"bill_type,omitempty"`

	// GmtPay 收费时间,时间精确到秒
	//
	// Example: 2023-05-16 22:22:22
	GmtPay *string `json:"gmt_pay,omitempty"`

	// IsRefund 是否退费
	//
	// Example: true
	IsRefund *bool `json:"is_refund,omitempty"`

	// OutBizNo 外部请求号
	//
	// Example: 2323232323
	OutBizNo *string `json:"out_biz_no,omitempty"`

	// PlanAmount 应收费金额，单位元
	//
	// Example: 0.02
	PlanAmount *string `json:"plan_amount,omitempty"`

	// ProductName 收费产品
	//
	// Example: ALI_ESCROW
	ProductName *string `json:"product_name,omitempty"`

	// ServiceTarget 收费唯一id
	//
	// Example: 2023232
	ServiceTarget *string `json:"service_target,omitempty"`

	// ServiceType 收费类型
	//
	// Example: TRADE
	ServiceType *string `json:"service_type,omitempty"`

	// Status 状态
	//
	// Example: 1
	Status *string `json:"status,omitempty"`

	// TargetAccountNo 收费目标账号
	//
	// Example: 20880156
	TargetAccountNo *string `json:"target_account_no,omitempty"`

	// TargetUserId 收费目标uid
	//
	// Example: 2088
	TargetUserId *string `json:"target_user_id,omitempty"`
}

// OpenApiRoyaltyDetailInfoPojo defines model for OpenApiRoyaltyDetailInfoPojo.
type OpenApiRoyaltyDetailInfoPojo struct {
	// Amount 分账的金额，单位为元
	Amount *string `json:"amount,omitempty"`

	// AmountPercentage 分账信息中分账百分比。取值范围为大于0，少于或等于100的整数。
	AmountPercentage *int `json:"amount_percentage,omitempty"`

	// Desc 分账描述
	Desc *string `json:"desc,omitempty"`

	// RoyaltyScene 可选值：达人佣金、平台服务费、技术服务费、其他
	RoyaltyScene *string `json:"royalty_scene,omitempty"`

	// RoyaltyType 分账类型.
	RoyaltyType *string `json:"royalty_type,omitempty"`

	// TransIn 收入方账户。如果收入方账户类型为userId，本参数为收入方的支付宝账号对应的支付宝唯一用户号，以2088开头的纯16位数字；如果收入方类型为cardAliasNo，本参数为收入方在支付宝绑定的卡编号；如果收入方类型为loginName，本参数为收入方的支付宝登录号；如果收入方类型为openId，本参数为收入方的支付宝openId信息
	TransIn *string `json:"trans_in,omitempty"`

	// TransInName 分账收款方姓名，上送则进行姓名与支付宝账号的一致性校验，校验不一致则分账失败。不上送则不进行姓名校验
	TransInName *string `json:"trans_in_name,omitempty"`

	// TransInType 收入方账户类型。
	TransInType *string `json:"trans_in_type,omitempty"`

	// TransOut 支出方账户。如果支出方账户类型为userId，本参数为支出方的支付宝账号对应的支付宝唯一用户号，以2088开头的纯16位数字；如果支出方类型为loginName，本参数为支出方的支付宝登录号。 泛金融类商户分账时，该字段不要上送。
	TransOut *string `json:"trans_out,omitempty"`

	// TransOutType 支出方账户类型。
	TransOutType *string `json:"trans_out_type,omitempty"`
}

// PaymentInfoWithId defines model for PaymentInfoWithId.
type PaymentInfoWithId struct {
	// PaymentIds 支付单id
	//
	// Example: ["23232334343242424","2323232323232"]
	PaymentIds *[]string `json:"payment_ids,omitempty"`

	// Type 支付资金类型
	//
	// Example: PAY
	Type *string `json:"type,omitempty"`
}

// PresetPayToolInfo defines model for PresetPayToolInfo.
type PresetPayToolInfo struct {
	// Amount 前置资产金额。单位：元。
	//
	// Example: 12.21
	Amount *[]string `json:"amount,omitempty"`

	// AssertTypeCode 前置资产类型编码，和收单支付传入的preset_pay_tool里面的类型编码保持一致。
	//
	// Example: HEMA
	AssertTypeCode *string `json:"assert_type_code,omitempty"`
}

// RefundChargeInfo defines model for RefundChargeInfo.
type RefundChargeInfo struct {
	// ChargeType 收单手续费trade，花呗分期手续hbfq，其他手续费charge
	ChargeType *string `json:"charge_type,omitempty"`

	// RefundChargeFee 实退费用。单位：元。
	RefundChargeFee *string `json:"refund_charge_fee,omitempty"`

	// RefundSubFeeDetailList 组合支付退费明细
	RefundSubFeeDetailList *[]RefundSubFee `json:"refund_sub_fee_detail_list,omitempty"`

	// SwitchFeeRate 签约费率
	SwitchFeeRate *string `json:"switch_fee_rate,omitempty"`
}

// RefundGoodsDetail defines model for RefundGoodsDetail.
type RefundGoodsDetail struct {
	// GoodsId 商品编号。	对应支付时传入的goods_id
	//
	// Example: apple-01
	GoodsId *string `json:"goods_id,omitempty"`

	// OutCertificateNoList 外部商品凭证编号列表
	//
	// Example: ["202407013232143241231243243423"]
	OutCertificateNoList *[]string `json:"out_certificate_no_list,omitempty"`

	// OutItemId 商家侧小程序商品ID，对应支付时传入的out_item_id
	//
	// Example: outItem_01
	OutItemId *string `json:"out_item_id,omitempty"`

	// OutSkuId 商家侧小程序商品sku ID，对应支付时传入的out_sku_id
	//
	// Example: outSku_01
	OutSkuId *string `json:"out_sku_id,omitempty"`

	// RefundAmount 该商品的退款总金额，单位为元
	//
	// Example: 19.50
	RefundAmount *string `json:"refund_amount,omitempty"`
}

// RefundRoyaltyResult defines model for RefundRoyaltyResult.
type RefundRoyaltyResult struct {
	// OriTransIn 商户请求的转入账号
	//
	// Example: 2088111111111111
	OriTransIn *string `json:"ori_trans_in,omitempty"`

	// OriTransOut 商户请求的转出账号
	//
	// Example: 2088111111111111
	OriTransOut *string `json:"ori_trans_out,omitempty"`

	// RefundAmount 退分账金额。单位：元。
	//
	// Example: 10
	RefundAmount *string `json:"refund_amount,omitempty"`

	// ResultCode 退分账结果码
	//
	// Example: SUCCESS
	ResultCode *string `json:"result_code,omitempty"`

	// RoyaltyType 分账类型.	字段为空默认为普通分账类型transfer
	//
	// Example: transfer
	RoyaltyType *string `json:"royalty_type,omitempty"`

	// TransIn 转入人支付宝账号对应用户ID
	//
	// Example: 2088102210397302
	TransIn *string `json:"trans_in,omitempty"`

	// TransInEmail 转入人支付宝账号
	//
	// Example: zen_gwen@hotmail.com
	TransInEmail *string `json:"trans_in_email,omitempty"`

	// TransOut 转出人支付宝账号对应用户ID
	//
	// Example: 2088102210397302
	TransOut *string `json:"trans_out,omitempty"`

	// TransOutEmail 转出人支付宝账号
	//
	// Example: alipay-test03@alipay.com
	TransOutEmail *string `json:"trans_out_email,omitempty"`
}

// RefundSubFee defines model for RefundSubFee.
type RefundSubFee struct {
	// RefundChargeFee 实退费用。单位：元。
	RefundChargeFee *string `json:"refund_charge_fee,omitempty"`

	// SwitchFeeRate 签约费率
	SwitchFeeRate *string `json:"switch_fee_rate,omitempty"`
}

// RoyaltyDetailInfos defines model for RoyaltyDetailInfos.
type RoyaltyDetailInfos struct {
	// Amount 分账的金额，单位为元
	Amount *string `json:"amount,omitempty"`

	// AmountPercentage 分账的比例，值为20代表按20%的比例分账
	AmountPercentage *string `json:"amount_percentage,omitempty"`

	// BatchNo 分账批次号
	// 	分账批次号。
	// 	目前需要和转入账号类型为bankIndex配合使用。
	BatchNo *string `json:"batch_no,omitempty"`

	// Desc 分账描述信息
	Desc *string `json:"desc,omitempty"`

	// OutRelationId 商户分账的外部关联号，用于关联到每一笔分账信息，商户需保证其唯一性。
	// 	如果为空，该值则默认为“商户网站唯一订单号+分账序列号”
	OutRelationId *string `json:"out_relation_id,omitempty"`

	// SerialNo 分账序列号，表示分账执行的顺序，必须为正整数
	SerialNo *int `json:"serial_no,omitempty"`

	// TransIn 如果转入账号类型为userId，本参数为接受分账金额的支付宝账号对应的支付宝唯一用户号。以2088开头的纯16位数字。
	// 	&#61548;	如果转入账号类型为bankIndex，本参数为28位的银行编号（商户和支付宝签约时确定）。
	// 	如果转入账号类型为storeId，本参数为商户的门店ID。
	TransIn *string `json:"trans_in,omitempty"`

	// TransInType 接受分账金额的账户类型
	TransInType *string `json:"trans_in_type,omitempty"`

	// TransOut 如果转出账号类型为userId，本参数为要分账的支付宝账号对应的支付宝唯一用户号。以2088开头的纯16位数字。
	TransOut *string `json:"trans_out,omitempty"`

	// TransOutType 要分账的账户类型。
	// 	目前只支持userId：支付宝账号对应的支付宝唯一用户号。
	// 	默认值为userId。
	TransOutType *string `json:"trans_out_type,omitempty"`
}

// RoyaltyInfo defines model for RoyaltyInfo.
type RoyaltyInfo struct {
	// RoyaltyDetailInfos 分账明细的信息，可以描述多条分账指令，json数组。
	RoyaltyDetailInfos *[]RoyaltyDetailInfos `json:"royalty_detail_infos,omitempty"`

	// RoyaltyType 分账类型
	// 	卖家的分账类型，目前只支持传入ROYALTY（普通分账类型）。
	RoyaltyType *string `json:"royalty_type,omitempty"`
}

// SettleDetailInfo defines model for SettleDetailInfo.
type SettleDetailInfo struct {
	// ActualAmount 仅在直付通账期模式下，当一笔交易需要分多次发起部分确认结算时使用，表示本次确认结算的实际结算金额。传递本字段后，原amount字段不再生效，结算金额以本字段为准。如已经发生过部分确认结算、不传递本字段则默认按剩余待结算金额一次性结算。
	ActualAmount *string `json:"actual_amount,omitempty"`

	// Amount 结算的金额，单位为元。在创建订单和支付接口时必须和交易金额相同。在结算确认接口时必须等于交易金额减去已退款金额。直付通账期模式下，如使用部分结算能力、传递了actual_amount字段，则忽略本字段的校验、可不传。
	Amount *string `json:"amount,omitempty"`

	// SettleEntityId 结算主体标识。当结算主体类型为SecondMerchant时，为二级商户的SecondMerchantID；当结算主体类型为Store时，为门店的外标。
	SettleEntityId *string `json:"settle_entity_id,omitempty"`

	// SettleEntityType 结算主体类型。
	SettleEntityType *string `json:"settle_entity_type,omitempty"`

	// SummaryDimension 结算汇总维度，按照这个维度汇总成批次结算，由商户指定。		目前需要和结算收款方账户类型为cardAliasNo配合使用
	SummaryDimension *string `json:"summary_dimension,omitempty"`

	// TransIn 结算收款方。当结算收款方类型是cardAliasNo时，本参数为用户在支付宝绑定的卡编号；结算收款方类型是userId时，本参数为用户的支付宝账号对应的支付宝唯一用户号，以2088开头的纯16位数字；当结算收款方类型是loginName时，本参数为用户的支付宝登录号；当结算收款方类型是defaultSettle时，本参数不能传值，保持为空。
	TransIn *string `json:"trans_in,omitempty"`

	// TransInType 结算收款方的账户类型。
	TransInType *string `json:"trans_in_type,omitempty"`
}

// SettleInfo defines model for SettleInfo.
type SettleInfo struct {
	// SettleDetailInfos 结算详细信息，json数组，目前只支持一条。
	SettleDetailInfos *[]SettleDetailInfo `json:"settle_detail_infos,omitempty"`

	// SettlePeriodTime 该笔订单的超期自动确认结算时间，到达期限后，将自动确认结算。此字段只在签约账期结算模式时有效。取值范围：1d～365d。d-天。 该参数数值不接受小数点。
	SettlePeriodTime *string `json:"settle_period_time,omitempty"`
}

// SubFee defines model for SubFee.
type SubFee struct {
	// ChargeFee 实收费用
	ChargeFee *string `json:"charge_fee,omitempty"`

	// OriginalChargeFee 原始费用
	OriginalChargeFee *string `json:"original_charge_fee,omitempty"`

	// SwitchFeeRate 签约费率
	SwitchFeeRate *string `json:"switch_fee_rate,omitempty"`
}

// SubMerchant defines model for SubMerchant.
type SubMerchant struct {
	// MerchantId 支付宝二级商户编号。	间连受理商户的支付宝商户编号，通过间连商户入驻接口后由支付宝生成。	直付通和机构间连业务场景下必传。
	MerchantId *string `json:"merchant_id,omitempty"`

	// MerchantType 二级商户编号类型。	枚举值：	alipay:支付宝分配的间联商户编号；	目前仅支持alipay，默认可以不传。
	MerchantType *string `json:"merchant_type,omitempty"`
}

// TapPayInfo defines model for TapPayInfo.
type TapPayInfo struct {
	// PaymentMediumType 碰一下支付的支付介质类型，标识当前支付为碰一下支付
	PaymentMediumType *string `json:"payment_medium_type,omitempty"`

	// TotalDiscountAmount 碰一下支付的碰一下共减优惠金额
	TotalDiscountAmount *string `json:"total_discount_amount,omitempty"`

	// TotalDiscountName 碰一下支付的碰一下共减金额展示名称
	TotalDiscountName *string `json:"total_discount_name,omitempty"`
}

// TradeFundBill defines model for TradeFundBill.
type TradeFundBill struct {
	// Amount 该支付工具类型所使用的金额。单位：元。
	Amount *string `json:"amount,omitempty"`

	// BankCode 银行卡支付时的银行代码
	BankCode *string `json:"bank_code,omitempty"`

	// FundChannel 交易使用的资金渠道，详见 <a href="https://opendocs.alipay.com/open/common/103259">支付渠道列表</a>
	FundChannel *string `json:"fund_channel,omitempty"`

	// FundType 渠道所使用的资金类型,目前只在资金渠道(fund_channel)是银行卡渠道(BANKCARD)的情况下才返回该信息
	FundType *string `json:"fund_type,omitempty"`

	// RealAmount 渠道实际付款金额
	RealAmount *string `json:"real_amount,omitempty"`
}

// TradeSettleDetail defines model for TradeSettleDetail.
type TradeSettleDetail struct {
	// Amount 实际操作金额，单位为元，两位小数。该参数的值为分账或补差或结算时传入
	//
	// Example: 10.00
	Amount *string `json:"amount,omitempty"`

	// OperationDt 操作日期
	//
	// Example: 2019-05-16 09:59:17
	OperationDt *string `json:"operation_dt,omitempty"`

	// OperationSerialNo 商户操作序列号。商户发起请求的外部请求号。
	//
	// Example: 2321232323232
	OperationSerialNo *string `json:"operation_serial_no,omitempty"`

	// OperationType 结算操作类型。有以下几种类型：	replenish(补差)、replenish_refund(退补差)、transfer(分账)、transfer_refund(退分账)、settle(结算)、settle_refund(退结算)、on_settle(待结算)。
	//
	// Example: replenish
	OperationType *string `json:"operation_type,omitempty"`

	// OriTransIn 商户请求的转入账号
	//
	// Example: 2088111111111111
	OriTransIn *string `json:"ori_trans_in,omitempty"`

	// OriTransOut 商户请求的转出账号
	//
	// Example: 2088111111111111
	OriTransOut *string `json:"ori_trans_out,omitempty"`

	// TransIn 转入账号
	//
	// Example: 2088111111111111
	TransIn *string `json:"trans_in,omitempty"`

	// TransOut 转出账号
	//
	// Example: 2088111111111111
	TransOut *string `json:"trans_out,omitempty"`
}

// TradeSettleInfo defines model for TradeSettleInfo.
type TradeSettleInfo struct {
	// TradeSettleDetailList 交易结算明细信息
	TradeSettleDetailList *[]TradeSettleDetail `json:"trade_settle_detail_list,omitempty"`

	// TradeUnsettledAmount 直付通账期、直连账期下返回，其他场景为空，表示一笔订单剩余待结算金额
	//
	// Example: 1.1
	TradeUnsettledAmount *string `json:"trade_unsettled_amount,omitempty"`
}

// VoucherDetail defines model for VoucherDetail.
type VoucherDetail struct {
	// Amount 优惠券面额，它应该会等于商家出资加上其他出资方出资
	Amount *string `json:"amount,omitempty"`

	// Id 券id
	Id *string `json:"id,omitempty"`

	// Memo 优惠券备注信息
	Memo *string `json:"memo,omitempty"`

	// MerchantContribute 商家出资（特指发起交易的商家出资金额）
	MerchantContribute *string `json:"merchant_contribute,omitempty"`

	// Name 券名称
	Name *string `json:"name,omitempty"`

	// OtherContribute 其他出资方出资金额，可能是支付宝，可能是品牌商，或者其他方，也可能是他们的一起出资
	OtherContribute *string `json:"other_contribute,omitempty"`

	// OtherContributeDetail 优惠券的其他出资方明细
	OtherContributeDetail *[]ContributeDetail `json:"other_contribute_detail,omitempty"`

	// PurchaseAntContribute 如果使用的这张券是用户购买的，则该字段代表用户在购买这张券时平台优惠的金额
	PurchaseAntContribute *string `json:"purchase_ant_contribute,omitempty"`

	// PurchaseBuyerContribute 如果使用的这张券是用户购买的，则该字段代表用户在购买这张券时用户实际付款的金额
	PurchaseBuyerContribute *string `json:"purchase_buyer_contribute,omitempty"`

	// PurchaseMerchantContribute 如果使用的这张券是用户购买的，则该字段代表用户在购买这张券时商户优惠的金额
	PurchaseMerchantContribute *string `json:"purchase_merchant_contribute,omitempty"`

	// TemplateId 券模板id
	TemplateId *string `json:"template_id,omitempty"`

	// Type 券类型
	Type *string `json:"type,omitempty"`
}

// AlipayDataDataserviceBillDownloadurlQueryParams defines parameters for AlipayDataDataserviceBillDownloadurlQuery.
type AlipayDataDataserviceBillDownloadurlQueryParams struct {
	// BillType 账单类型，商户通过接口或商户经开放平台授权后其所属服务商通过接口可以获取以下账单类型。
	BillType *string `form:"bill_type,omitempty" json:"bill_type,omitempty"`

	// BillDate 账单时间：	<p> * 日账单格式为yyyy-MM-dd，最早可下载近6年的日账单。不支持下载当日账单，只能下载前一日24点前的账单数据（T+1），当日数据一般于次日 9 点前生成，特殊情况可能延迟。</p>	<p> * 月账单格式为yyyy-MM，最早可下载近6年的月账单。不支持下载当月账单，只能下载上一月账单数据，当月账单一般在次月 3 日生成，特殊情况可能延迟。</p>	<p> * 当biz_type为settlementMerge时候，时间为汇总批次结算资金到账的日期，日期格式为yyyy-MM-dd，最早可下载<u>2023年4月17日</u>及以后的账单。</p>	<p> * 接口调用仅支持下载近6年的账单，更多账单请前往 b.alipay.com 对账中心-账单下载页下载。</p>
	BillDate *string `form:"bill_date,omitempty" json:"bill_date,omitempty"`

	// Smid 二级商户smid，这个参数只在bill_type是trade_zft_merchant时才能使用
	Smid *string `form:"smid,omitempty" json:"smid,omitempty"`
}

// AlipayTradeCloseJSONRequestBody defines body for AlipayTradeClose for application/json ContentType.
type AlipayTradeCloseJSONRequestBody = AlipayTradeCloseModel

// AlipayTradeFastpayRefundQueryJSONRequestBody defines body for AlipayTradeFastpayRefundQuery for application/json ContentType.
type AlipayTradeFastpayRefundQueryJSONRequestBody = AlipayTradeFastpayRefundQueryModel

// AlipayTradePrecreateJSONRequestBody defines body for AlipayTradePrecreate for application/json ContentType.
type AlipayTradePrecreateJSONRequestBody = AlipayTradePrecreateModel

// AlipayTradeQueryJSONRequestBody defines body for AlipayTradeQuery for application/json ContentType.
type AlipayTradeQueryJSONRequestBody = AlipayTradeQueryModel

// AlipayTradeRefundJSONRequestBody defines body for AlipayTradeRefund for application/json ContentType.
type AlipayTradeRefundJSONRequestBody = AlipayTradeRefundModel
